import { useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { api } from "../api";
import { useAuth } from "../auth";
import { ErrorBox, PageHeader } from "../components/UI";
import { applyFontSizePreference, readFontSizePreference, type FontSizePreference } from "../fontsize";
import { useT } from "../i18n/LangContext";
import { readProgressLinksPreference, writeProgressLinksPreference } from "../progress-links";
export function ProfilePage() {
  const t = useT(); const { user, refresh } = useAuth(); const [enabled, setEnabled] = useState(!!user?.email_notifications); const [progressLinksEnabled, setProgressLinksEnabled] = useState(readProgressLinksPreference); const [fontSize, setFontSize] = useState<FontSizePreference>(readFontSizePreference); const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const saveNotice = async () => { await api("/profile", { method: "PATCH", body: JSON.stringify({ email_notifications: enabled }) }); await refresh(); setMessage(t("profile.noticeSaved")); };
  const password = async (event: FormEvent) => { event.preventDefault(); setError(""); try { await api("/auth/change-password", { method: "POST", body: JSON.stringify({ current_password: current, new_password: next }) }); setCurrent(""); setNext(""); setMessage(t("profile.passwordChanged")); } catch (cause) { setError(cause instanceof Error ? cause.message : t("auth.changeFailed")); } };
  const chooseFontSize = (value: FontSizePreference) => { setFontSize(value); applyFontSizePreference(value); setMessage(t("profile.fontSaved")); };
  const chooseProgressLinks = (value: boolean) => { setProgressLinksEnabled(value); writeProgressLinksPreference(value); setMessage(t("profile.progressLinksSaved")); };
  return <><PageHeader title={t("profile.title")} description={`${user?.name} · ${user?.email} · ${user?.group_name}`} />{error && <ErrorBox message={error} />}{message && <div className="mb-4 rounded-lg border border-ok bg-void p-3 text-sm text-ok">{message}</div>}<div className="grid gap-6 md:grid-cols-2"><section className="panel"><h2 className="mb-4 font-bold">{t("profile.display")}</h2><label className="label" htmlFor="font-size">{t("profile.fontSize")}</label><select id="font-size" className="mb-5 w-full" value={fontSize} onChange={(event) => chooseFontSize(event.target.value as FontSizePreference)}><option value="standard">{t("profile.fontStandard")}</option><option value="large">{t("profile.fontLarge")}</option></select><label className="mb-4 flex items-center gap-3 text-sm"><input type="checkbox" checked={progressLinksEnabled} onChange={(event) => chooseProgressLinks(event.target.checked)} />{t("profile.progressLinks")}</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={enabled} onChange={(e) => setEnabled(e.target.checked)} />{t("profile.emailDigest")}</label><button className="btn mt-5" onClick={() => void saveNotice()}>{t("profile.saveNotice")}</button></section><form className="panel" onSubmit={password}><h2 className="mb-4 font-bold">{t("profile.changePassword")}</h2><label className="label">{t("auth.currentPassword")}</label><input className="mb-3 w-full" type="password" value={current} onChange={(e) => setCurrent(e.target.value)} required /><label className="label">{t("auth.newPassword")}</label><input className="mb-4 w-full" type="password" minLength={8} value={next} onChange={(e) => setNext(e.target.value)} required /><button className="btn">{t("profile.changePassword")}</button></form></div><p className="mt-6 text-sm text-star-dim">{t("profile.forcedHint")} <Link className="text-psi" to="/change-password">{t("profile.forcedLink")}</Link>.</p></>;
}
