import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { Line, LineChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api, formatDate, patchBody, today } from "../api";
import { CHART } from "../chartTheme";
import { Empty, ErrorBox, Loading, Markdown, PageHeader, ProgressBar, RiskBadge } from "../components/UI";
import type { BdCase, Metadata, ProgressUpdate, ProjectDetail } from "../types";
import { TaskWorkspace } from "../components/TaskViews";
import { ProjectFiles } from "../components/ProjectFiles";
import { AutomationPanel } from "../components/AutomationPanel";
import { OkrPanel } from "../components/OkrPanel";
import { QaPanel } from "../components/QaPanel";
import { useLang, useT } from "../i18n/LangContext";
import type { TransKey } from "../i18n/translations";
import { ProgressLinkDialog } from "../components/ProgressLinkDialog";
import { readProgressLinksPreference, type ProgressLinksResponse } from "../progress-links";
import { formatProgressEditedAt, isAutoGeneratedProgressUpdate } from "../progress-updates";

const baseTabs: Array<[string, TransKey]> = [["overview", "project.tab.overview"], ["tasks", "project.tab.tasks"], ["updates", "project.tab.updates"]];
const bdStatuses: Array<[string, TransKey]> = [["準備文件", "bd.preparing"], ["已送件", "bd.submitted"], ["審查中", "bd.review"], ["補件中", "bd.supplement"], ["核准", "bd.approved"], ["結案", "bd.closed"]];
const bdFeeCategories: Array<[string, TransKey]> = [["規費", "bd.official"], ["顧問費", "bd.consulting"], ["檢驗費", "bd.testing"], ["其他", "bd.other"]];

export function ProjectDetailPage() {
  const t = useT();
  const { id = "" } = useParams(); const navigate = useNavigate(); const [params] = useSearchParams(); const [data, setData] = useState<ProjectDetail | null>(null); const [meta, setMeta] = useState<Metadata | null>(null); const [tab, setTab] = useState("overview"); const [error, setError] = useState("");
  const load = () => api<ProjectDetail>(`/projects/${id}`).then(setData).catch((cause) => setError(cause instanceof Error ? cause.message : t("error.load")));
  useEffect(() => { void load(); }, [id]); useEffect(() => { void api<Metadata>("/metadata").then(setMeta); }, []);
  useEffect(() => { if (params.get("tour") === "automation") setTab("automation"); else if (params.get("tour") === "tasks" || params.get("task")) setTab("tasks"); }, [params]);
  if (error) return <ErrorBox message={error} />; if (!data) return <Loading />;
  const tabs: Array<[string, TransKey]> = [...baseTabs, ...(data.project.group_type === "clinical" ? [["clinical", "project.tab.clinical"]] as Array<[string, TransKey]> : []), ...(data.project.group_type === "bd" ? [["bd", "project.tab.bd"]] as Array<[string, TransKey]> : []), ...(data.project.group_type === "qa" ? [["qa", "project.tab.qa"]] as Array<[string, TransKey]> : []), ["files", "project.tab.files"], ["automation", "project.tab.automation"]];
  const remove = async () => { if (window.confirm(t("project.deleteConfirm"))) { await api(`/projects/${id}`, { method: "DELETE" }); navigate("/projects"); } };
  const status = { active: t("status.active"), paused: t("status.paused"), done: t("status.done"), archived: t("status.archived") };
  return <><PageHeader title={`${data.project.visibility === "private" ? "🔒 " : ""}${data.project.name}`} description={`${data.project.group_name} · ${t("common.owner", { name: data.project.owner_name })}`} actions={<div className="flex gap-2"><span className="badge">{status[data.project.status]}</span>{data.permissions.can_manage && <button className="btn-danger !py-1.5" onClick={() => void remove()}>{t("common.delete")}</button>}</div>} />
    <div data-tour="project-tabs" className="mb-5 flex gap-1 overflow-x-auto border-b border-nexus-line">{tabs.map(([key, label]) => <button key={key} className={`border-b-2 px-4 py-3 text-sm font-medium ${tab === key ? "border-psi text-psi" : "border-transparent text-star-dim"}`} onClick={() => setTab(key)}>{t(label)}</button>)}</div>
    {tab === "overview" && <Overview data={data} metadata={meta} reload={load} />}
    {tab === "tasks" && <TaskWorkspace data={data} metadata={meta} reload={load} />}
    {tab === "updates" && <Updates data={data} reload={load} />}
    {tab === "clinical" && <Clinical data={data} reload={load} />}
    {tab === "bd" && <Bd data={data} reload={load} />}
    {tab === "qa" && <QaPanel projectId={id} />}
    {tab === "files" && <ProjectFiles projectId={id} canEdit={data.permissions.can_edit} onChanged={load} />}
    {tab === "automation" && <AutomationPanel data={data} metadata={meta} />}
  </>;
}

const submitData = (event: FormEvent<HTMLFormElement>) => Object.fromEntries(new FormData(event.currentTarget).entries());

function Overview({ data, metadata, reload }: { data: ProjectDetail; metadata: Metadata | null; reload(): void }) {
  const { lang } = useLang();
  const t = useT();
  const [progress, setProgress] = useState(data.project.progress); const [riskBusy, setRiskBusy] = useState(false); const [riskError, setRiskError] = useState(""); const [milestoneSubmitting, setMilestoneSubmitting] = useState(false); const [milestoneError, setMilestoneError] = useState("");
  useEffect(() => setProgress(data.project.progress), [data.project.progress]);
  const saveProgress = async () => { await api(`/projects/${data.project.id}`, patchBody({ progress })); reload(); };
  const addMilestone = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = event.currentTarget;
    setMilestoneSubmitting(true); setMilestoneError("");
    try {
      await api(`/projects/${data.project.id}/milestones`, { method: "POST", body: JSON.stringify(submitData(event)) });
      form.reset();
      reload();
    } catch (cause) {
      setMilestoneError(cause instanceof Error ? cause.message : t("error.create"));
    } finally {
      setMilestoneSubmitting(false);
    }
  };
  const toggleMilestone = async (id: string, done: boolean) => { await api(`/milestones/${id}`, patchBody({ done })); reload(); };
  const saveSettings = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/projects/${data.project.id}`, patchBody(submitData(event))); reload(); };
  const addMember = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/projects/${data.project.id}/members`, { method: "POST", body: JSON.stringify(submitData(event)) }); reload(); };
  const archive = async () => { await api(`/projects/${data.project.id}/${data.project.status === "archived" ? "unarchive" : "archive"}`, { method: "POST" }); reload(); };
  const analyzeRisk = async () => { setRiskBusy(true); setRiskError(""); try { await api("/ai/project-risk", { method: "POST", body: JSON.stringify({ project_id: data.project.id, lang }) }); reload(); } catch (cause) { setRiskError(cause instanceof Error ? cause.message : t("project.analysisFailed")); } finally { setRiskBusy(false); } };
  const suggestions = (() => { try { const parsed: unknown = JSON.parse(data.project.risk_suggestions || "[]"); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string") : []; } catch { return []; } })();
  return <><div className="grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2"><section className="panel"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">{t("project.goal")}</h2>{data.permissions.can_manage && <label className="flex items-center gap-2 text-sm">{t("project.progressMode")}<select value={data.project.progress_mode} onChange={(e) => void api(`/projects/${data.project.id}`, patchBody({ progress_mode: e.target.value })).then(reload)}><option value="manual">{t("project.manual")}</option><option value="auto">{t("project.auto")}</option></select></label>}</div><p className="mt-3 text-sm leading-6 text-star-dim">{data.project.goal_summary || t("project.noGoal")}</p><div className="mt-6"><div className="mb-2 flex justify-between text-sm"><span>{t("project.overallProgress")} {data.project.progress_mode === "auto" && <span className="text-psi">{t("project.autoHint")}</span>}</span><span className="font-bold">{progress}%</span></div>{data.project.progress_mode === "manual" ? <><input className="w-full" type="range" min="0" max="100" value={progress} disabled={!data.permissions.can_edit} onChange={(e) => setProgress(Number(e.target.value))} />{data.permissions.can_edit && <button className="btn mt-3" onClick={() => void saveProgress()}>{t("project.saveProgress")}</button>}</> : <ProgressBar value={data.project.progress} />}</div></section>
    <section className="panel"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><h2 className="font-bold">{t("project.aiRisk")}</h2><RiskBadge level={data.project.risk_level} /></div>{data.permissions.can_edit && <button className="btn-secondary" disabled={riskBusy} onClick={() => void analyzeRisk()}>{t(riskBusy ? "views.analyzing" : "project.reanalyze")}</button>}</div>{riskError && <ErrorBox message={riskError} />}<p className="mt-4 text-sm leading-6 text-star-dim">{data.project.risk_summary || t("project.noRisk")}</p>{suggestions.length > 0 && <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-star-dim">{suggestions.map((item) => <li key={item}>{item}</li>)}</ul>}</section>
    <section className="panel"><h2 className="mb-4 font-bold">{t("project.milestones")}</h2>{milestoneError && <ErrorBox message={milestoneError} />}<div className="space-y-2">{data.milestones.map((item) => <label className={`flex items-center gap-3 rounded-lg border p-3 ${!item.done && item.due_date && item.due_date < today() ? "border-danger bg-danger/10" : "border-nexus-line"}`} key={item.id}><input type="checkbox" checked={!!item.done} disabled={!data.permissions.can_edit} onChange={(e) => void toggleMilestone(item.id, e.target.checked)} /><span className={`flex-1 text-sm ${item.done ? "text-star-dim line-through" : ""}`}>{item.title}</span><span className="text-xs text-star-dim">{item.due_date || t("common.notScheduled")}</span></label>)}</div>{data.permissions.can_edit && <form className="mt-4 flex flex-wrap gap-2" onSubmit={addMilestone}><input name="title" placeholder={t("project.newMilestone")} required /><input name="due_date" type="date" /><button className="btn" disabled={milestoneSubmitting}>{t(milestoneSubmitting ? "common.processing" : "common.add")}</button></form>}</section></div>
    <aside className="space-y-6"><section className="panel"><h2 className="mb-3 font-bold">{t("project.info")}</h2><dl className="space-y-3 text-sm"><div><dt className="text-star-dim">{t("project.startDate")}</dt><dd>{data.project.start_date || t("common.none")}</dd></div><div><dt className="text-star-dim">{t("project.targetDate")}</dt><dd>{data.project.target_date || t("common.none")}</dd></div><div><dt className="text-star-dim">{t("project.recentActivity")}</dt><dd>{formatDate(data.project.last_activity_at, true, lang)}</dd></div></dl></section>
    <section className="panel"><h2 className="mb-3 font-bold">{t("project.members")}</h2><div className="space-y-2">{data.members.map((member) => <div className="flex justify-between text-sm" key={member.id}><span>{member.name}<span className="ml-1 text-xs text-star-dim">{member.role}</span></span>{data.permissions.can_manage && <button className="text-xs text-danger" onClick={() => void api(`/projects/${data.project.id}/members/${member.id}`, { method: "DELETE" }).then(reload)}>{t("common.remove")}</button>}</div>)}</div>{data.permissions.can_manage && metadata && <form className="mt-4 flex gap-2" onSubmit={addMember}><select className="min-w-0 flex-1" name="user_id">{metadata.users.filter((user) => !data.members.some((member) => member.id === user.id) && user.id !== data.project.owner_id).map((user) => <option value={user.id} key={user.id}>{user.name}</option>)}</select><button className="btn !px-3">{t("project.join")}</button></form>}</section>
    {data.permissions.can_manage && <form className="panel space-y-3" onSubmit={saveSettings}><h2 className="font-bold">{t("project.settings")}</h2><label className="label">{t("project.visibility")}</label><select className="w-full" name="visibility" defaultValue={data.project.visibility}><option value="all">{t("projects.visibility.all")}</option><option value="group">{t("projects.visibility.group")}</option><option value="private">{t("projects.visibility.private")}</option></select><label className="label">{t("common.status")}</label><select className="w-full" name="status" defaultValue={data.project.status}><option value="active">{t("status.active")}</option><option value="paused">{t("status.paused")}</option><option value="done">{t("status.done")}</option><option value="archived">{t("status.archived")}</option></select><button className="btn w-full">{t("project.saveSettings")}</button><button type="button" className="btn-secondary w-full" onClick={() => void archive()}>{t(data.project.status === "archived" ? "project.restore" : "project.archiveNow")}</button></form>}</aside></div><OkrPanel projectId={data.project.id} metadata={metadata} onChanged={reload} /></>;
}

function Updates({ data, reload }: { data: ProjectDetail; reload(): void }) {
  const { lang } = useLang();
  const t = useT();
  const [content, setContent] = useState(""); const [raw, setRaw] = useState(""); const [busy, setBusy] = useState(false); const [links, setLinks] = useState<ProgressLinksResponse | null>(null); const [toast, setToast] = useState("");
  const draft = async () => { if (!raw.trim()) return; setBusy(true); try { const result = await api<{ draft: string }>("/ai/draft-update", { method: "POST", body: JSON.stringify({ raw_text: raw, project_id: data.project.id, lang }) }); setContent(result.draft); } finally { setBusy(false); } };
  const save = async () => {
    const publishedContent = content;
    const result = await api<{ id: string }>(`/projects/${data.project.id}/progress-updates`, { method: "POST", body: JSON.stringify({ content: publishedContent, progress_snapshot: data.project.progress }) });
    setContent(""); setRaw(""); reload();
    if (!readProgressLinksPreference()) return;
    try {
      const suggestions = await api<ProgressLinksResponse>("/ai/progress-links", { method: "POST", body: JSON.stringify({ project_id: data.project.id, content: publishedContent, progress_update_id: result.id, lang }) });
      if (suggestions.complete.length || suggestions.create.length || suggestions.milestones.length || suggestions.dates.length) setLinks(suggestions);
    } catch (error) {
      console.warn("progress link suggestions unavailable", error);
    }
  };
  const applied = ({ completed, created, milestones, dates }: { completed: number; created: number; milestones: number; dates: number }) => {
    reload();
    setToast(t("progressLinks.appliedToast", { completed, created, milestones, dates }));
    window.setTimeout(() => setToast(""), 3500);
  };
  return <>{toast && <div className="fixed bottom-5 right-5 z-[60] border border-ok bg-nexus p-4 text-sm text-ok shadow-2xl" role="status">{toast}</div>}<div className="grid gap-6 lg:grid-cols-5"><section className="panel lg:col-span-2"><h2 className="mb-4 font-bold">{t("project.newUpdate")}</h2>{data.permissions.can_edit ? <><textarea className="mb-3 min-h-24 w-full" placeholder={t("project.rawPlaceholder")} value={raw} onChange={(e) => setRaw(e.target.value)} /><button className="btn-secondary mb-4" disabled={busy} onClick={() => void draft()}>{t(busy ? "project.organizing" : "project.aiDraft")}</button><textarea className="min-h-48 w-full" placeholder={t("project.updatePlaceholder")} value={content} onChange={(e) => setContent(e.target.value)} /><button className="btn mt-3" disabled={!content.trim()} onClick={() => void save()}>{t("project.publish")}</button></> : <p className="text-sm text-star-dim">{t("project.noEdit")}</p>}</section><section className="space-y-4 lg:col-span-3">{data.progress_updates.length ? data.progress_updates.map((item) => <ProgressUpdateCard item={item} reload={reload} key={item.id} />) : <Empty>{t("project.noUpdates")}</Empty>}</section></div>{links && <ProgressLinkDialog response={links} projectId={data.project.id} stages={data.stages} tasks={data.tasks} onClose={() => setLinks(null)} onApplied={applied} />}</>;
}

function ProgressUpdateCard({ item, reload }: { item: ProgressUpdate; reload(): void }) {
  const { lang } = useLang();
  const t = useT();
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(item.content);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const save = async () => {
    if (!draft.trim()) return;
    setBusy(true); setError("");
    try {
      await api(`/progress-updates/${item.id}`, patchBody({ content: draft }));
      setEditing(false);
      reload();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : t("error.update"));
    } finally {
      setBusy(false);
    }
  };
  const remove = async () => {
    if (!window.confirm(t("project.deleteUpdateConfirm"))) return;
    setBusy(true); setError("");
    try {
      await api(`/progress-updates/${item.id}`, { method: "DELETE" });
      reload();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : t("error.operation"));
    } finally {
      setBusy(false);
    }
  };
  const cancel = () => { setDraft(item.content); setEditing(false); setError(""); };
  return <article className="panel"><div className="mb-3 flex items-start justify-between gap-3 text-xs text-star-dim"><span>{item.author_name}{item.is_support ? t("project.supportBy", { name: item.author_name }) : ""}</span><div className="flex items-center gap-1"><span>{formatDate(item.created_at, true, lang)}</span>{item.can_edit && <><button type="button" className="progress-update-edit" data-progress-update-edit aria-label={t("project.editUpdate")} title={t("project.editUpdate")} disabled={busy} onClick={() => { setDraft(item.content); setEditing(true); }}><svg aria-hidden="true" viewBox="0 0 24 24"><path d="m4 20 4.2-1 10.6-10.6-3.2-3.2L5 15.8 4 20Zm9.8-13 3.2 3.2M14.8 6l1.7-1.7a1.5 1.5 0 0 1 2.1 0l1.1 1.1a1.5 1.5 0 0 1 0 2.1L18 9.2" /></svg></button><button type="button" className="regwatch-row-delete" data-progress-update-delete aria-label={t("project.deleteUpdate")} title={t("project.deleteUpdate")} disabled={busy} onClick={() => void remove()}><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3m3 0-1 13H7L6 7m4 4v5m4-5v5" /></svg></button></>}</div></div>{error && <ErrorBox message={error} />}{editing ? <div><textarea className="min-h-32 w-full" value={draft} onChange={(event) => setDraft(event.target.value)} /><div className="mt-3 flex gap-2"><button className="btn" type="button" disabled={busy || !draft.trim()} onClick={() => void save()}>{t("common.save")}</button><button className="btn-secondary" type="button" disabled={busy} onClick={cancel}>{t("common.cancel")}</button></div></div> : <Markdown content={item.content} />}{item.edited_at && <p className="mt-3 text-xs text-star-dim">{t("project.editedAt", { date: formatProgressEditedAt(item.edited_at, lang) })}</p>}{isAutoGeneratedProgressUpdate(item.content) && <p className="mt-3 text-xs text-star-dim">{t("project.autoDeleteHint")}</p>}{item.progress_snapshot !== null && <div className="mt-4"><ProgressBar value={item.progress_snapshot} /></div>}</article>;
}

function Clinical({ data, reload }: { data: ProjectDetail; reload(): void }) {
  const t = useT(); const { lang } = useLang();
  const [enrollmentSubmitting, setEnrollmentSubmitting] = useState(false);
  const target = data.clinical_settings?.target_n ?? 0; let total = 0; const chart = data.enrollments.map((item) => ({ date: item.record_date, 累計收案: total += Number(item.count), 目標: target })); const sites = data.enrollments.reduce<Record<string, number>>((result, item) => { const site = item.site || "未指定"; result[site] = (result[site] ?? 0) + Number(item.count); return result; }, {});
  const add = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = event.currentTarget; setEnrollmentSubmitting(true);
    try { await api(`/projects/${data.project.id}/clinical/enrollments`, { method: "POST", body: JSON.stringify(submitData(event)) }); form.reset(); reload(); }
    finally { setEnrollmentSubmitting(false); }
  };
  const setTarget = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/projects/${data.project.id}/clinical/settings`, { method: "PUT", body: JSON.stringify(submitData(event)) }); reload(); };
  return <div className="space-y-6"><div className="grid gap-6 lg:grid-cols-3"><section className="panel lg:col-span-2"><h2 className="mb-4 font-bold">{t("clinical.cumulative")}</h2><ResponsiveContainer width="100%" height={300}><LineChart data={chart}><CartesianGrid stroke={CHART.line} strokeDasharray="3 3" /><XAxis dataKey="date" tick={{ fill: CHART.starDim }} /><YAxis tick={{ fill: CHART.starDim }} /><Tooltip /><Legend /><Line name={t("dashboard.enrollment")} dataKey="累計收案" stroke={CHART.psi} strokeWidth={3} /><Line name={t("dashboard.target")} dataKey="目標" stroke={CHART.gold} strokeDasharray="4 4" /></LineChart></ResponsiveContainer></section><section className="panel"><p className="text-sm text-star-dim">{t("clinical.current")}</p><p className="my-2 text-4xl font-black text-psi">{total} <span className="text-base text-star-dim">/ {t("common.people", { count: target })}</span></p>{data.permissions.can_edit && <form className="mt-6 flex gap-2" onSubmit={setTarget}><input className="min-w-0 flex-1" name="target_n" type="number" min="0" defaultValue={target} /><button className="btn">{t("clinical.updateTarget")}</button></form>}</section></div>
    {data.permissions.can_edit && <form className="panel grid gap-3 md:grid-cols-5" onSubmit={add}><input name="record_date" type="date" defaultValue={today()} required /><input name="site" placeholder={t("clinical.site")} /><input name="count" type="number" min="0" placeholder={t("clinical.newCount")} required /><input name="note" placeholder={t("common.notes")} /><button className="btn" disabled={enrollmentSubmitting}>{t(enrollmentSubmitting ? "common.processing" : "clinical.record")}</button></form>}
    <div className="grid gap-6 lg:grid-cols-3"><section className="panel lg:col-span-2"><h2 className="mb-3 font-bold">{t("clinical.daily")}</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-nexus-line text-gold-bright"><th className="py-2">{t("common.date")}</th><th>{t("clinical.site")}</th><th>{t("clinical.count")}</th><th>{t("common.notes")}</th></tr></thead><tbody>{data.enrollments.map((item) => <tr className="border-b border-nexus-line" key={item.id}><td className="py-2">{item.record_date}</td><td>{item.site || t("common.none")}</td><td>{item.count}</td><td>{item.note}</td></tr>)}</tbody></table></div></section><section className="panel"><h2 className="mb-3 font-bold">{t("clinical.siteTotals")}</h2>{Object.entries(sites).map(([site, count]) => <div className="flex justify-between border-b py-2 text-sm" key={site}><span>{site}</span><strong>{t("common.people", { count })}</strong></div>)}</section></div></div>;
}

function Bd({ data, reload }: { data: ProjectDetail; reload(): void }) {
  const t = useT();
  const { lang } = useLang();
  const [feeSubmitting, setFeeSubmitting] = useState(false);
  const addCase = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/projects/${data.project.id}/bd/cases`, { method: "POST", body: JSON.stringify(submitData(event)) }); event.currentTarget.reset(); reload(); };
  const addEvent = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = submitData(event); const caseId = String(values.case_id); delete values.case_id; await api(`/bd/cases/${caseId}/events`, { method: "POST", body: JSON.stringify(values) }); event.currentTarget.reset(); reload(); };
  const addFee = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = event.currentTarget; setFeeSubmitting(true);
    try { await api(`/projects/${data.project.id}/bd/fees`, { method: "POST", body: JSON.stringify(submitData(event)) }); form.reset(); reload(); }
    finally { setFeeSubmitting(false); }
  };
  return <div className="space-y-6">{data.permissions.can_edit && <form className="panel grid gap-3 md:grid-cols-4" onSubmit={addCase}><h2 className="font-bold md:col-span-4">{t("bd.newCase")}</h2><input name="case_name" placeholder={t("bd.caseName")} required /><input name="product_name" placeholder={t("bd.product")} required /><input name="case_type" placeholder={t("bd.caseType")} required /><input name="submission_no" placeholder={t("bd.submissionNo")} /><select name="current_status">{bdStatuses.map(([value, key]) => <option value={value} key={value}>{t(key)}</option>)}</select><input name="submitted_at" type="date" /><input name="expected_approval" type="date" /><button className="btn">{t("bd.addCase")}</button></form>}
    <div className="grid gap-4 md:grid-cols-2">{data.bd_cases.map((item) => <CaseCard key={item.id} item={item} canEdit={data.permissions.can_edit} reload={reload} events={data.bd_events.filter((event) => event.case_id === item.id)} />)}</div>
    {data.permissions.can_edit && data.bd_cases.length > 0 && <form className="panel grid gap-3 md:grid-cols-5" onSubmit={addEvent}><h2 className="font-bold md:col-span-5">{t("bd.newHistory")}</h2><select name="case_id">{data.bd_cases.map((item) => <option value={item.id} key={item.id}>{item.case_name}</option>)}</select><input name="event_date" type="date" defaultValue={today()} required /><input name="event_type" placeholder={t("bd.eventPlaceholder")} required /><input name="description" placeholder={t("common.description")} required /><button className="btn">{t("bd.addHistory")}</button></form>}
    {data.permissions.can_view_fees && <section className="panel"><h2 className="mb-4 font-bold">{t("bd.fees")}</h2>{data.permissions.can_edit && <form className="mb-4 grid gap-3 md:grid-cols-6" onSubmit={addFee}><input name="fee_date" type="date" defaultValue={today()} required /><select name="case_id"><option value="">{t("bd.noCase")}</option>{data.bd_cases.map((item) => <option value={item.id} key={item.id}>{item.case_name}</option>)}</select><select name="category">{bdFeeCategories.map(([value, key]) => <option value={value} key={value}>{t(key)}</option>)}</select><input name="amount" type="number" min="0" placeholder={t("bd.amount")} required /><input name="currency" defaultValue="TWD" /><button className="btn" disabled={feeSubmitting}>{t(feeSubmitting ? "common.processing" : "bd.addFee")}</button></form>}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-nexus-line text-gold-bright"><th className="py-2">{t("common.date")}</th><th>{t("common.category")}</th><th>{t("bd.amount")}</th><th>{t("common.notes")}</th></tr></thead><tbody>{data.bd_fees?.map((fee) => <tr className="border-b border-nexus-line" key={fee.id}><td className="py-2">{fee.fee_date}</td><td>{t(bdFeeCategories.find(([value]) => value === fee.category)?.[1] ?? "bd.other")}</td><td>{fee.currency} {Number(fee.amount).toLocaleString(lang === "en" ? "en-US" : "zh-TW")}</td><td>{fee.note}</td></tr>)}</tbody></table></div><p className="mt-4 text-right font-bold">{t("bd.subtotal")}: TWD {(data.bd_fees ?? []).filter((fee) => fee.currency === "TWD").reduce((sum, fee) => sum + Number(fee.amount), 0).toLocaleString(lang === "en" ? "en-US" : "zh-TW")}</p></section>}</div>;
}

function CaseCard({ item, events, canEdit, reload }: { item: BdCase; events: ProjectDetail["bd_events"]; canEdit: boolean; reload(): void }) {
  const t = useT();
  const setStatus = async (status: string) => { await api(`/bd/cases/${item.id}`, patchBody({ current_status: status })); reload(); };
  return <article className="panel"><div className="flex justify-between gap-3"><div><p className="text-xs text-star-dim">{item.case_type} · {item.product_name}</p><h3 className="mt-1 font-bold">{item.case_name}</h3></div><select value={item.current_status} disabled={!canEdit} onChange={(e) => void setStatus(e.target.value)}>{bdStatuses.map(([value, key]) => <option value={value} key={value}>{t(key)}</option>)}</select></div><p className="mt-3 text-sm text-star-dim">{t("bd.submissionNo")}: {item.submission_no || "—"} · {t("bd.expectedApproval", { date: item.expected_approval || "—" })}</p><div className="mt-4 space-y-3 border-l-2 border-gold-dim pl-4">{events.map((event) => <div key={event.id}><p className="text-sm font-medium">{event.event_type} · {event.event_date}</p><p className="text-xs text-star-dim">{event.description}</p></div>)}</div></article>;
}
