import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { Line, LineChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api, formatDate, patchBody, today } from "../api";
import { CHART } from "../chartTheme";
import { Empty, ErrorBox, Loading, Markdown, PageHeader, ProgressBar, RiskBadge } from "../components/UI";
import type { BdCase, Metadata, ProjectDetail } from "../types";
import { TaskWorkspace } from "../components/TaskViews";
import { ProjectFiles } from "../components/ProjectFiles";
import { AutomationPanel } from "../components/AutomationPanel";
import { OkrPanel } from "../components/OkrPanel";
import { QaPanel } from "../components/QaPanel";

const baseTabs = [["overview", "總覽"], ["tasks", "任務"], ["updates", "進度紀錄"]] as const;

export function ProjectDetailPage() {
  const { id = "" } = useParams(); const navigate = useNavigate(); const [params] = useSearchParams(); const [data, setData] = useState<ProjectDetail | null>(null); const [meta, setMeta] = useState<Metadata | null>(null); const [tab, setTab] = useState("overview"); const [error, setError] = useState("");
  const load = () => api<ProjectDetail>(`/projects/${id}`).then(setData).catch((cause) => setError(cause instanceof Error ? cause.message : "載入失敗"));
  useEffect(() => { void load(); }, [id]); useEffect(() => { void api<Metadata>("/metadata").then(setMeta); }, []);
  useEffect(() => { if (params.get("tour") === "automation") setTab("automation"); else if (params.get("tour") === "tasks" || params.get("task")) setTab("tasks"); }, [params]);
  if (error) return <ErrorBox message={error} />; if (!data) return <Loading />;
  const tabs = [...baseTabs, ...(data.project.group_type === "clinical" ? [["clinical", "臨床"]] as const : []), ...(data.project.group_type === "bd" ? [["bd", "BD"]] as const : []), ...(data.project.group_type === "qa" ? [["qa", "QA"]] as const : []), ["files", "檔案"], ["automation", "自動化"]] as const;
  const remove = async () => { if (window.confirm("刪除後無法復原，確定刪除此專案？")) { await api(`/projects/${id}`, { method: "DELETE" }); navigate("/projects"); } };
  return <><PageHeader title={`${data.project.visibility === "private" ? "🔒 " : ""}${data.project.name}`} description={`${data.project.group_name} · Owner：${data.project.owner_name}`} actions={<div className="flex gap-2"><span className="badge">{statusLabel[data.project.status]}</span>{data.permissions.can_manage && <button className="btn-danger !py-1.5" onClick={() => void remove()}>刪除</button>}</div>} />
    <div data-tour="project-tabs" className="mb-5 flex gap-1 overflow-x-auto border-b border-nexus-line">{tabs.map(([key, label]) => <button key={key} className={`border-b-2 px-4 py-3 text-sm font-medium ${tab === key ? "border-psi text-psi" : "border-transparent text-star-dim"}`} onClick={() => setTab(key)}>{label}</button>)}</div>
    {tab === "overview" && <Overview data={data} metadata={meta} reload={load} />}
    {tab === "tasks" && <TaskWorkspace data={data} metadata={meta} reload={load} />}
    {tab === "updates" && <Updates data={data} reload={load} />}
    {tab === "clinical" && <Clinical data={data} reload={load} />}
    {tab === "bd" && <Bd data={data} reload={load} />}
    {tab === "qa" && <QaPanel projectId={id} />}
    {tab === "files" && <ProjectFiles projectId={id} canEdit={data.permissions.can_edit} onChanged={load} />}
    {tab === "automation" && <AutomationPanel data={data} metadata={meta} />}
  </>;
}

const statusLabel: Record<string, string> = { active: "進行中", paused: "暫停", done: "完成", archived: "已歸檔" };
const submitData = (event: FormEvent<HTMLFormElement>) => Object.fromEntries(new FormData(event.currentTarget).entries());

function Overview({ data, metadata, reload }: { data: ProjectDetail; metadata: Metadata | null; reload(): void }) {
  const [progress, setProgress] = useState(data.project.progress); const [riskBusy, setRiskBusy] = useState(false); const [riskError, setRiskError] = useState("");
  useEffect(() => setProgress(data.project.progress), [data.project.progress]);
  const saveProgress = async () => { await api(`/projects/${data.project.id}`, patchBody({ progress })); reload(); };
  const addMilestone = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/projects/${data.project.id}/milestones`, { method: "POST", body: JSON.stringify(submitData(event)) }); event.currentTarget.reset(); reload(); };
  const toggleMilestone = async (id: string, done: boolean) => { await api(`/milestones/${id}`, patchBody({ done })); reload(); };
  const saveSettings = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/projects/${data.project.id}`, patchBody(submitData(event))); reload(); };
  const addMember = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/projects/${data.project.id}/members`, { method: "POST", body: JSON.stringify(submitData(event)) }); reload(); };
  const archive = async () => { await api(`/projects/${data.project.id}/${data.project.status === "archived" ? "unarchive" : "archive"}`, { method: "POST" }); reload(); };
  const analyzeRisk = async () => { setRiskBusy(true); setRiskError(""); try { await api("/ai/project-risk", { method: "POST", body: JSON.stringify({ project_id: data.project.id }) }); reload(); } catch (cause) { setRiskError(cause instanceof Error ? cause.message : "分析失敗"); } finally { setRiskBusy(false); } };
  const suggestions = (() => { try { const parsed: unknown = JSON.parse(data.project.risk_suggestions || "[]"); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string") : []; } catch { return []; } })();
  return <><div className="grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2"><section className="panel"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">專案目標</h2>{data.permissions.can_manage && <label className="flex items-center gap-2 text-sm">進度模式<select value={data.project.progress_mode} onChange={(e) => void api(`/projects/${data.project.id}`, patchBody({ progress_mode: e.target.value })).then(reload)}><option value="manual">手動</option><option value="auto">自動</option></select></label>}</div><p className="mt-3 text-sm leading-6 text-star-dim">{data.project.goal_summary || "尚未設定專案目標。"}</p><div className="mt-6"><div className="mb-2 flex justify-between text-sm"><span>整體進度 {data.project.progress_mode === "auto" && <span className="text-psi">（依任務、里程碑、待辦與 KR 自動計算）</span>}</span><span className="font-bold">{progress}%</span></div>{data.project.progress_mode === "manual" ? <><input className="w-full" type="range" min="0" max="100" value={progress} disabled={!data.permissions.can_edit} onChange={(e) => setProgress(Number(e.target.value))} />{data.permissions.can_edit && <button className="btn mt-3" onClick={() => void saveProgress()}>儲存進度</button>}</> : <ProgressBar value={data.project.progress} />}</div></section>
    <section className="panel"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><h2 className="font-bold">AI 專案風險</h2><RiskBadge level={data.project.risk_level} /></div>{data.permissions.can_edit && <button className="btn-secondary" disabled={riskBusy} onClick={() => void analyzeRisk()}>{riskBusy ? "分析中…" : "重新分析"}</button>}</div>{riskError && <ErrorBox message={riskError} />}<p className="mt-4 text-sm leading-6 text-star-dim">{data.project.risk_summary || "尚未分析；可依時程、逾期與最近進度產生風險預測。"}</p>{suggestions.length > 0 && <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-star-dim">{suggestions.map((item) => <li key={item}>{item}</li>)}</ul>}</section>
    <section className="panel"><h2 className="mb-4 font-bold">里程碑</h2><div className="space-y-2">{data.milestones.map((item) => <label className={`flex items-center gap-3 rounded-lg border p-3 ${!item.done && item.due_date && item.due_date < today() ? "border-danger bg-danger/10" : "border-nexus-line"}`} key={item.id}><input type="checkbox" checked={!!item.done} disabled={!data.permissions.can_edit} onChange={(e) => void toggleMilestone(item.id, e.target.checked)} /><span className={`flex-1 text-sm ${item.done ? "text-star-dim line-through" : ""}`}>{item.title}</span><span className="text-xs text-star-dim">{item.due_date || "未排程"}</span></label>)}</div>{data.permissions.can_edit && <form className="mt-4 flex flex-wrap gap-2" onSubmit={addMilestone}><input name="title" placeholder="新增里程碑" required /><input name="due_date" type="date" /><button className="btn">新增</button></form>}</section></div>
    <aside className="space-y-6"><section className="panel"><h2 className="mb-3 font-bold">專案資訊</h2><dl className="space-y-3 text-sm"><div><dt className="text-star-dim">起始日</dt><dd>{data.project.start_date || "—"}</dd></div><div><dt className="text-star-dim">目標日</dt><dd>{data.project.target_date || "—"}</dd></div><div><dt className="text-star-dim">最近活動</dt><dd>{formatDate(data.project.last_activity_at, true)}</dd></div></dl></section>
    <section className="panel"><h2 className="mb-3 font-bold">成員</h2><div className="space-y-2">{data.members.map((member) => <div className="flex justify-between text-sm" key={member.id}><span>{member.name}<span className="ml-1 text-xs text-star-dim">{member.role}</span></span>{data.permissions.can_manage && <button className="text-xs text-danger" onClick={() => void api(`/projects/${data.project.id}/members/${member.id}`, { method: "DELETE" }).then(reload)}>移除</button>}</div>)}</div>{data.permissions.can_manage && metadata && <form className="mt-4 flex gap-2" onSubmit={addMember}><select className="min-w-0 flex-1" name="user_id">{metadata.users.filter((user) => !data.members.some((member) => member.id === user.id) && user.id !== data.project.owner_id).map((user) => <option value={user.id} key={user.id}>{user.name}</option>)}</select><button className="btn !px-3">加入</button></form>}</section>
    {data.permissions.can_manage && <form className="panel space-y-3" onSubmit={saveSettings}><h2 className="font-bold">專案設定</h2><label className="label">可見性</label><select className="w-full" name="visibility" defaultValue={data.project.visibility}><option value="all">全公司</option><option value="group">同組＋成員</option><option value="private">保密</option></select><label className="label">狀態</label><select className="w-full" name="status" defaultValue={data.project.status}><option value="active">進行中</option><option value="paused">暫停</option><option value="done">完成</option><option value="archived">歸檔</option></select><button className="btn w-full">儲存設定</button><button type="button" className="btn-secondary w-full" onClick={() => void archive()}>{data.project.status === "archived" ? "還原專案" : "立即歸檔"}</button></form>}</aside></div><OkrPanel projectId={data.project.id} metadata={metadata} onChanged={reload} /></>;
}

function Updates({ data, reload }: { data: ProjectDetail; reload(): void }) {
  const [content, setContent] = useState(""); const [raw, setRaw] = useState(""); const [busy, setBusy] = useState(false);
  const draft = async () => { if (!raw.trim()) return; setBusy(true); try { const result = await api<{ draft: string }>("/ai/draft-update", { method: "POST", body: JSON.stringify({ raw_text: raw, project_id: data.project.id }) }); setContent(result.draft); } finally { setBusy(false); } };
  const save = async () => { await api(`/projects/${data.project.id}/progress-updates`, { method: "POST", body: JSON.stringify({ content, progress_snapshot: data.project.progress }) }); setContent(""); setRaw(""); reload(); };
  return <div className="grid gap-6 lg:grid-cols-5"><section className="panel lg:col-span-2"><h2 className="mb-4 font-bold">新增進度</h2>{data.permissions.can_edit ? <><textarea className="mb-3 min-h-24 w-full" placeholder="輸入零散筆記，交給 AI 整理…" value={raw} onChange={(e) => setRaw(e.target.value)} /><button className="btn-secondary mb-4" disabled={busy} onClick={() => void draft()}>{busy ? "整理中…" : "AI 快寫"}</button><textarea className="min-h-48 w-full" placeholder="可編輯的進度內容" value={content} onChange={(e) => setContent(e.target.value)} /><button className="btn mt-3" disabled={!content.trim()} onClick={() => void save()}>發布進度</button></> : <p className="text-sm text-star-dim">您沒有填寫權限。</p>}</section><section className="space-y-4 lg:col-span-3">{data.progress_updates.length ? data.progress_updates.map((item) => <article className="panel" key={item.id}><div className="mb-3 flex justify-between gap-3 text-xs text-star-dim"><span>{item.author_name}{item.is_support ? ` · 由${item.author_name}支援填寫` : ""}</span><span>{formatDate(item.created_at, true)}</span></div><Markdown content={item.content} />{item.progress_snapshot !== null && <div className="mt-4"><ProgressBar value={item.progress_snapshot} /></div>}</article>) : <Empty>尚無進度紀錄</Empty>}</section></div>;
}

function Clinical({ data, reload }: { data: ProjectDetail; reload(): void }) {
  const target = data.clinical_settings?.target_n ?? 0; let total = 0; const chart = data.enrollments.map((item) => ({ date: item.record_date, 累計收案: total += Number(item.count), 目標: target })); const sites = data.enrollments.reduce<Record<string, number>>((result, item) => { const site = item.site || "未指定"; result[site] = (result[site] ?? 0) + Number(item.count); return result; }, {});
  const add = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/projects/${data.project.id}/clinical/enrollments`, { method: "POST", body: JSON.stringify(submitData(event)) }); event.currentTarget.reset(); reload(); };
  const setTarget = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/projects/${data.project.id}/clinical/settings`, { method: "PUT", body: JSON.stringify(submitData(event)) }); reload(); };
  return <div className="space-y-6"><div className="grid gap-6 lg:grid-cols-3"><section className="panel lg:col-span-2"><h2 className="mb-4 font-bold">累計收案 vs 目標</h2><ResponsiveContainer width="100%" height={300}><LineChart data={chart}><CartesianGrid stroke={CHART.line} strokeDasharray="3 3" /><XAxis dataKey="date" tick={{ fill: CHART.starDim }} /><YAxis tick={{ fill: CHART.starDim }} /><Tooltip /><Legend /><Line dataKey="累計收案" stroke={CHART.psi} strokeWidth={3} /><Line dataKey="目標" stroke={CHART.gold} strokeDasharray="4 4" /></LineChart></ResponsiveContainer></section><section className="panel"><p className="text-sm text-star-dim">目前累計</p><p className="my-2 text-4xl font-black text-psi">{total} <span className="text-base text-star-dim">/ {target} 人</span></p>{data.permissions.can_edit && <form className="mt-6 flex gap-2" onSubmit={setTarget}><input className="min-w-0 flex-1" name="target_n" type="number" min="0" defaultValue={target} /><button className="btn">更新目標</button></form>}</section></div>
    {data.permissions.can_edit && <form className="panel grid gap-3 md:grid-cols-5" onSubmit={add}><input name="record_date" type="date" defaultValue={today()} required /><input name="site" placeholder="中心" /><input name="count" type="number" min="0" placeholder="新增人數" required /><input name="note" placeholder="備註" /><button className="btn">登錄收案</button></form>}
    <div className="grid gap-6 lg:grid-cols-3"><section className="panel lg:col-span-2"><h2 className="mb-3 font-bold">逐日紀錄</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-nexus-line text-gold-bright"><th className="py-2">日期</th><th>中心</th><th>人數</th><th>備註</th></tr></thead><tbody>{data.enrollments.map((item) => <tr className="border-b border-nexus-line" key={item.id}><td className="py-2">{item.record_date}</td><td>{item.site || "—"}</td><td>{item.count}</td><td>{item.note}</td></tr>)}</tbody></table></div></section><section className="panel"><h2 className="mb-3 font-bold">中心小計</h2>{Object.entries(sites).map(([site, count]) => <div className="flex justify-between border-b py-2 text-sm" key={site}><span>{site}</span><strong>{count} 人</strong></div>)}</section></div></div>;
}

function Bd({ data, reload }: { data: ProjectDetail; reload(): void }) {
  const addCase = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/projects/${data.project.id}/bd/cases`, { method: "POST", body: JSON.stringify(submitData(event)) }); event.currentTarget.reset(); reload(); };
  const addEvent = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = submitData(event); const caseId = String(values.case_id); delete values.case_id; await api(`/bd/cases/${caseId}/events`, { method: "POST", body: JSON.stringify(values) }); event.currentTarget.reset(); reload(); };
  const addFee = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/projects/${data.project.id}/bd/fees`, { method: "POST", body: JSON.stringify(submitData(event)) }); event.currentTarget.reset(); reload(); };
  return <div className="space-y-6">{data.permissions.can_edit && <form className="panel grid gap-3 md:grid-cols-4" onSubmit={addCase}><h2 className="font-bold md:col-span-4">新增查驗登記案件</h2><input name="case_name" placeholder="案名" required /><input name="product_name" placeholder="產品" required /><input name="case_type" placeholder="類別（如 NDA）" required /><input name="submission_no" placeholder="送件號" /><select name="current_status"><option>準備文件</option><option>已送件</option><option>審查中</option><option>補件中</option><option>核准</option><option>結案</option></select><input name="submitted_at" type="date" /><input name="expected_approval" type="date" /><button className="btn">新增案件</button></form>}
    <div className="grid gap-4 md:grid-cols-2">{data.bd_cases.map((item) => <CaseCard key={item.id} item={item} canEdit={data.permissions.can_edit} reload={reload} events={data.bd_events.filter((event) => event.case_id === item.id)} />)}</div>
    {data.permissions.can_edit && data.bd_cases.length > 0 && <form className="panel grid gap-3 md:grid-cols-5" onSubmit={addEvent}><h2 className="font-bold md:col-span-5">新增案件歷程</h2><select name="case_id">{data.bd_cases.map((item) => <option value={item.id} key={item.id}>{item.case_name}</option>)}</select><input name="event_date" type="date" defaultValue={today()} required /><input name="event_type" placeholder="事件（如補件通知）" required /><input name="description" placeholder="說明" required /><button className="btn">新增歷程</button></form>}
    {data.permissions.can_view_fees && <section className="panel"><h2 className="mb-4 font-bold">費用紀錄</h2>{data.permissions.can_edit && <form className="mb-4 grid gap-3 md:grid-cols-6" onSubmit={addFee}><input name="fee_date" type="date" defaultValue={today()} required /><select name="case_id"><option value="">不指定案件</option>{data.bd_cases.map((item) => <option value={item.id} key={item.id}>{item.case_name}</option>)}</select><select name="category"><option>規費</option><option>顧問費</option><option>檢驗費</option><option>其他</option></select><input name="amount" type="number" min="0" placeholder="金額" required /><input name="currency" defaultValue="TWD" /><button className="btn">新增費用</button></form>}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-nexus-line text-gold-bright"><th className="py-2">日期</th><th>類別</th><th>金額</th><th>備註</th></tr></thead><tbody>{data.bd_fees?.map((fee) => <tr className="border-b border-nexus-line" key={fee.id}><td className="py-2">{fee.fee_date}</td><td>{fee.category}</td><td>{fee.currency} {Number(fee.amount).toLocaleString("zh-TW")}</td><td>{fee.note}</td></tr>)}</tbody></table></div><p className="mt-4 text-right font-bold">小計：TWD {(data.bd_fees ?? []).filter((fee) => fee.currency === "TWD").reduce((sum, fee) => sum + Number(fee.amount), 0).toLocaleString("zh-TW")}</p></section>}</div>;
}

function CaseCard({ item, events, canEdit, reload }: { item: BdCase; events: ProjectDetail["bd_events"]; canEdit: boolean; reload(): void }) {
  const setStatus = async (status: string) => { await api(`/bd/cases/${item.id}`, patchBody({ current_status: status })); reload(); };
  return <article className="panel"><div className="flex justify-between gap-3"><div><p className="text-xs text-star-dim">{item.case_type} · {item.product_name}</p><h3 className="mt-1 font-bold">{item.case_name}</h3></div><select value={item.current_status} disabled={!canEdit} onChange={(e) => void setStatus(e.target.value)}><option>準備文件</option><option>已送件</option><option>審查中</option><option>補件中</option><option>核准</option><option>結案</option></select></div><p className="mt-3 text-sm text-star-dim">送件號：{item.submission_no || "—"}　預計核准：{item.expected_approval || "—"}</p><div className="mt-4 space-y-3 border-l-2 border-gold-dim pl-4">{events.map((event) => <div key={event.id}><p className="text-sm font-medium">{event.event_type} · {event.event_date}</p><p className="text-xs text-star-dim">{event.description}</p></div>)}</div></article>;
}
