import { useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { api } from "../api";
import { useAuth } from "../auth";
import { Empty, ErrorBox, Loading, PageHeader, ProgressBar } from "../components/UI";
import { useT } from "../i18n/LangContext";
import type { Metadata, Project } from "../types";

export function ProjectsPage() {
  const { user } = useAuth(); const t = useT(); const [projects, setProjects] = useState<Project[] | null>(null); const [meta, setMeta] = useState<Metadata | null>(null); const [showNew, setShowNew] = useState(false); const [filters, setFilters] = useState({ group: "", status: "", keyword: "" });
  const load = () => { const query = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)); api<{ projects: Project[] }>(`/projects?${query}`).then((data) => setProjects(data.projects)); };
  useEffect(load, [filters]); useEffect(() => { api<Metadata>("/metadata").then(setMeta); }, []);
  const statusLabel = { active: t("status.active"), paused: t("status.paused"), done: t("status.done"), archived: t("status.archived") };
  return <><PageHeader title={t("nav.projects")} description={t("projects.description")} actions={user?.role !== "intern" && <button className="btn" onClick={() => setShowNew(!showNew)}>{t("projects.new")}</button>} />
    {showNew && meta && <NewProject metadata={meta} onDone={() => { setShowNew(false); load(); }} />}
    <div className="panel mb-5 grid gap-3 md:grid-cols-3"><select value={filters.group} onChange={(e) => setFilters({ ...filters, group: e.target.value })}><option value="">{t("projects.allGroups")}</option>{meta?.groups.map((g) => <option key={g.id} value={g.id}>{g.name}</option>)}</select><select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">{t("projects.allStatuses")}</option><option value="active">{t("status.active")}</option><option value="paused">{t("status.paused")}</option><option value="done">{t("status.done")}</option><option value="archived">{t("status.archived")}</option></select><input placeholder={t("projects.search")} value={filters.keyword} onChange={(e) => setFilters({ ...filters, keyword: e.target.value })} /></div>
    {!projects ? <Loading /> : projects.length ? <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{projects.map((project, index) => <Link data-tour={index === 0 ? "project-card" : undefined} to={`/projects/${project.id}`} className="panel transition hover:shadow-[0_0_16px_rgb(var(--color-psi)/.28)]" key={project.id}><div className="mb-4 flex items-start justify-between gap-2"><div><span className="badge mb-2">{project.group_name}</span><h2 className="font-bold">{project.visibility === "private" && "🔒 "}{project.name}</h2></div><span className="text-xs text-star-dim">{statusLabel[project.status]}</span></div><p className="mb-4 line-clamp-2 min-h-10 text-sm text-star-dim">{project.description || t("projects.noDescription")}</p><ProgressBar value={project.progress} /><div className="mt-4 flex justify-between text-xs text-star-dim"><span>{t("common.owner", { name: project.owner_name })}</span><span>{t("common.target", { date: project.target_date || t("common.none") })}</span></div></Link>)}</div> : <Empty>{t("projects.notFound")}</Empty>}
  </>;
}

function NewProject({ metadata, onDone }: { metadata: Metadata; onDone(): void }) {
  const t = useT(); const [form, setForm] = useState({ name: "", description: "", group_id: metadata.groups[0]?.id ?? "", visibility: "group", template_id: "", target_date: "" }); const [error, setError] = useState("");
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); try { await api("/projects", { method: "POST", body: JSON.stringify(form) }); onDone(); } catch (cause) { setError(cause instanceof Error ? cause.message : t("error.create")); } };
  return <form onSubmit={submit} className="panel mb-5"><h2 className="mb-4 font-bold">{t("projects.createTitle")}</h2>{error && <ErrorBox message={error} />}<div className="grid gap-3 md:grid-cols-3"><input placeholder={t("projects.namePlaceholder")} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /><select value={form.group_id} onChange={(e) => setForm({ ...form, group_id: e.target.value })}>{metadata.groups.map((g) => <option value={g.id} key={g.id}>{g.name}</option>)}</select><select value={form.visibility} onChange={(e) => setForm({ ...form, visibility: e.target.value })}><option value="all">{t("projects.visibility.all")}</option><option value="group">{t("projects.visibility.group")}</option><option value="private">{t("projects.visibility.private")}</option></select><input className="md:col-span-2" placeholder={t("projects.descriptionPlaceholder")} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><input type="date" value={form.target_date} onChange={(e) => setForm({ ...form, target_date: e.target.value })} /><select value={form.template_id} onChange={(e) => setForm({ ...form, template_id: e.target.value })}><option value="">{t("projects.noTemplate")}</option>{metadata.templates.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><button className="btn">{t("projects.create")}</button></div></form>;
}
