import { Suspense, lazy, useEffect, useMemo, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { api, formatDate, patchBody, today } from "../api";
import { CHART } from "../chartTheme";
import { Empty, ErrorBox, Loading, Markdown, PageHeader, ProgressBar, RiskBadge } from "../components/UI";
import type { BdCase, BdEvent, Metadata, ProgressUpdate, Project, ProjectDetail } from "../types";
import { relatedProjects } from "../project-grouping";
import { groupProjectsForSwitch, nextProjectId, type SwitchableProject } from "../project-switcher";
import { PROJECT_CHANGED } from "../components/AiSidebar";
import { TaskWorkspace } from "../components/TaskViews";
import { ProjectFiles } from "../components/ProjectFiles";
import { AutomationPanel } from "../components/AutomationPanel";
import { OkrPanel } from "../components/OkrPanel";
import { QaPanel } from "../components/QaPanel";
import { useLang, useT } from "../i18n/LangContext";
import type { TransKey } from "../i18n/translations";
import { ProgressLinkDialog } from "../components/ProgressLinkDialog";
import { readProgressLinksPreference, type ProgressLinksResponse } from "../progress-links";
import { ProgressComposer } from "../components/ProgressComposer";
import { planEntryActions, type ProgressEntry } from "../progress-entry";
import { formatProgressEditedAt, isAutoGeneratedProgressUpdate } from "../progress-updates";
import { HelpTip } from "../components/HelpTip";
import { ProjectTimeline } from "../components/ProjectTimeline";

const EnrollmentChart = lazy(() => import("../components/EnrollmentChart"));

const baseTabs: Array<[string, TransKey]> = [["overview", "project.tab.overview"], ["tasks", "project.tab.tasks"], ["updates", "project.tab.updates"]];
function projectTabs(groupType: string): Array<[string, TransKey]> {
  const extra: Array<[string, TransKey]> = groupType === "clinical" ? [["clinical", "project.tab.clinical"]]
    : groupType === "bd" ? [["bd", "project.tab.bd"]]
      : groupType === "qa" ? [["qa", "project.tab.qa"]] : [];
  return [...baseTabs, ...extra, ["files", "project.tab.files"], ["automation", "project.tab.automation"]];
}

/** 開啟這些分頁時才去取對應區段；其餘分頁只需要 core。 */
const tabSection: Record<string, string | undefined> = { updates: "updates", clinical: "clinical", bd: "bd" };

const bdStatuses: Array<[string, TransKey]> =[["準備文件", "bd.preparing"], ["已送件", "bd.submitted"], ["審查中", "bd.review"], ["補件中", "bd.supplement"], ["核准", "bd.approved"], ["結案", "bd.closed"]];
const bdFeeCategories: Array<[string, TransKey]> = [["規費", "bd.official"], ["顧問費", "bd.consulting"], ["檢驗費", "bd.testing"], ["其他", "bd.other"]];

export function ProjectDetailPage() {
  const t = useT();
  const { id = "" } = useParams(); const navigate = useNavigate(); const [params] = useSearchParams(); const [data, setData] = useState<ProjectDetail | null>(null); const [meta, setMeta] = useState<Metadata | null>(null); const [tab, setTab] = useState("overview"); const [error, setError] = useState("");
  const [siblings, setSiblings] = useState<SwitchableProject[]>([]);
  const [sections, setSections] = useState<string[]>(["core"]);
  // 每次都請求「core ＋ 目前已載入的區段」，回應永遠是完整的，不需要合併舊資料。
  const load = (list: string[] = sections) => api<ProjectDetail>(`/projects/${id}?sections=${list.join(",")}`)
    .then((result) => { setData(result); setSections(list); })
    .catch((cause) => setError(cause instanceof Error ? cause.message : t("error.load")));
  useEffect(() => { setData(null); setError(""); setSections(["core"]); void load(["core"]); }, [id]);
  useEffect(() => { void api<Metadata>("/metadata").then(setMeta); }, []);
  useEffect(() => {
    const need = tabSection[tab];
    if (need && !sections.includes(need)) void load([...sections, need]);
  }, [tab, sections]);
  useEffect(() => { void api<{ projects: SwitchableProject[] }>("/projects?summary=1").then((result) => setSiblings(result.projects)).catch(() => setSiblings([])); }, []);
  // AI 小幫手側邊欄掛在 Layout 上，寫入後拿不到這裡的 load()，改用事件通知重抓。
  useEffect(() => {
    const refresh = (event: Event) => { if ((event as CustomEvent<{ projectId?: string }>).detail?.projectId === id) void load(); };
    window.addEventListener(PROJECT_CHANGED, refresh);
    return () => window.removeEventListener(PROJECT_CHANGED, refresh);
  }, [id, sections]);
  const groupType = data?.project.group_type;
  useEffect(() => { if (groupType && !projectTabs(groupType).some(([key]) => key === tab)) setTab("overview"); }, [groupType]);
  useEffect(() => {
    const tour = params.get("tour");
    if (tour === "automation" || tour === "files" || tour === "updates" || tour === "overview") setTab(tour);
    else if (tour === "tasks" || params.get("task")) setTab("tasks");
  }, [params]);
  if (error) return <ErrorBox message={error} />; if (!data) return <Loading />;
  const tabs = projectTabs(data.project.group_type);
  const remove = async () => { if (window.confirm(t("project.deleteConfirm"))) { await api(`/projects/${id}`, { method: "DELETE" }); navigate("/projects"); } };
  const status = { active: t("status.active"), paused: t("status.paused"), done: t("status.done"), archived: t("status.archived") };
  return <><PageHeader title={`${data.project.visibility === "private" ? "🔒 " : ""}${data.project.name}`} description={`${data.project.group_name} · ${t("common.owner", { name: data.project.owner_name })}`} actions={<div className="flex flex-wrap items-center gap-2"><ProjectSwitcher projects={siblings} current={data.project} /><span className="badge">{status[data.project.status]}</span>{data.permissions.can_manage && <button className="btn-danger !py-1.5" onClick={() => void remove()}>{t("common.delete")}</button>}</div>} />
    <RelatedStrip current={data.project} siblings={siblings} />
    <div data-tour="project-tabs" className="project-tabs mb-5 flex gap-1">{tabs.map(([key, label]) => <button key={key} className={`border-b-2 px-4 py-3 text-sm font-medium ${tab === key ? "border-psi text-psi" : "border-transparent text-star-dim"}`} onClick={() => setTab(key)}>{t(label)}</button>)}</div>
    {tab === "overview" && <Overview data={data} metadata={meta} reload={load} />}
    {tab === "tasks" && <TaskWorkspace data={data} metadata={meta} reload={load} />}
    {tab === "updates" && <Updates data={data} reload={load} />}
    {tab === "clinical" && <Clinical data={data} reload={load} />}
    {tab === "bd" && <Bd data={data} reload={load} />}
    {tab === "qa" && <QaPanel projectId={id} />}
    {tab === "files" && <ProjectFiles projectId={id} canEdit={data.permissions.can_edit} onChanged={load} />}
    {tab === "automation" && <AutomationPanel data={data} metadata={meta} />}
  </>;
}

function ProjectSwitcher({ projects, current }: { projects: SwitchableProject[]; current: Project }) {
  const t = useT();
  const navigate = useNavigate();
  if (projects.length < 2) return null;
  const groups = groupProjectsForSwitch(projects, current.group_id);
  const nextId = nextProjectId(projects, current);
  return <div data-project-switcher className="flex w-full items-center gap-2 sm:w-auto">
    <select className="touch-target min-w-0 flex-1 !py-1.5 text-sm sm:max-w-56 sm:flex-none" aria-label={t("project.switchLabel")} value={current.id} onChange={(event) => { if (event.target.value !== current.id) navigate(`/projects/${event.target.value}`); }}>
      {groups.map((group) => <optgroup key={group.id} label={group.isCurrentGroup ? `${group.name}（${t("project.currentGroup")}）` : group.name}>
        {group.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}
      </optgroup>)}
    </select>
    {nextId && <button className="btn-secondary touch-target whitespace-nowrap !py-1.5" title={t("project.nextProjectHint")} onClick={() => navigate(`/projects/${nextId}`)}>{t("project.nextProject")}</button>}
  </div>;
}

const submitData = (event: FormEvent<HTMLFormElement>) => Object.fromEntries(new FormData(event.currentTarget).entries());
const milestoneDateLabel = (dueDate: string | null, endDate: string | null, fallback: string) => dueDate ? `${dueDate}${endDate ? ` ~ ${endDate}` : ""}` : fallback;

function Overview({ data, metadata, reload }: { data: ProjectDetail; metadata: Metadata | null; reload(): void }) {
  const { lang } = useLang();
  const t = useT();
  const [progress, setProgress] = useState(data.project.progress); const [riskBusy, setRiskBusy] = useState(false); const [riskError, setRiskError] = useState("");
  useEffect(() => setProgress(data.project.progress), [data.project.progress]);
  const saveProgress = async () => { await api(`/projects/${data.project.id}`, patchBody({ progress })); reload(); };
  const saveSettings = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/projects/${data.project.id}`, patchBody(submitData(event))); reload(); };
  const addMember = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/projects/${data.project.id}/members`, { method: "POST", body: JSON.stringify(submitData(event)) }); reload(); };
  const archive = async () => { await api(`/projects/${data.project.id}/${data.project.status === "archived" ? "unarchive" : "archive"}`, { method: "POST" }); reload(); };
  const analyzeRisk = async () => { setRiskBusy(true); setRiskError(""); try { await api("/ai/project-risk", { method: "POST", body: JSON.stringify({ project_id: data.project.id, lang }) }); reload(); } catch (cause) { setRiskError(cause instanceof Error ? cause.message : t("project.analysisFailed")); } finally { setRiskBusy(false); } };
  const suggestions = (() => { try { const parsed: unknown = JSON.parse(data.project.risk_suggestions || "[]"); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string") : []; } catch { return []; } })();
  return <><div data-tour="project-overview" className="grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2"><section className="panel"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">{t("project.goal")}<HelpTip topic="projectGoal" /></h2>{data.permissions.can_manage && <label className="flex items-center gap-2 text-sm">{t("project.progressMode")}<HelpTip topic="progressMode" /><select aria-label={t("a11y.progressMode")} value={data.project.progress_mode} onChange={(e) => void api(`/projects/${data.project.id}`, patchBody({ progress_mode: e.target.value })).then(reload)}><option value="manual">{t("project.manual")}</option><option value="auto">{t("project.auto")}</option></select></label>}</div><p className="mt-3 text-sm leading-6 text-star-dim">{data.project.goal_summary || t("project.noGoal")}</p><div className="mt-6"><div className="mb-2 flex justify-between text-sm"><span>{t("project.overallProgress")}<HelpTip topic="progressMode" /> {data.project.progress_mode === "auto" && <span className="text-psi">{t("project.autoHint")}</span>}</span><span className="font-bold">{progress}%</span></div>{data.project.progress_mode === "manual" ? <><input aria-label={t("a11y.progressSlider")} className="w-full" type="range" min="0" max="100" value={progress} disabled={!data.permissions.can_edit} onChange={(e) => setProgress(Number(e.target.value))} />{data.permissions.can_edit && <button className="btn mt-3" onClick={() => void saveProgress()}>{t("project.saveProgress")}</button>}</> : <ProgressBar value={data.project.progress} />}</div></section>
    <section className="panel"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><h2 className="font-bold">{t("project.aiRisk")}<HelpTip topic="aiRisk" /></h2><RiskBadge level={data.project.risk_level} /></div>{data.permissions.can_edit && <button className="btn-secondary" disabled={riskBusy} onClick={() => void analyzeRisk()}>{t(riskBusy ? "views.analyzing" : "project.reanalyze")}</button>}</div>{riskError && <ErrorBox message={riskError} />}<p className="mt-4 text-sm leading-6 text-star-dim">{data.project.risk_summary || t("project.noRisk")}</p>{suggestions.length > 0 && <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-star-dim">{suggestions.map((item) => <li key={item}>{item}</li>)}</ul>}</section>
    <ProjectTimeline projectId={data.project.id} milestones={data.milestones} canEdit={data.permissions.can_edit} reload={reload} /></div>
    <aside className="space-y-6"><section className="panel"><h2 className="mb-3 font-bold">{t("project.info")}<HelpTip topic="projectDates" /></h2><dl className="space-y-3 text-sm"><div><dt className="text-star-dim">{t("project.startDate")}</dt><dd>{data.project.start_date || t("common.none")}</dd></div><div><dt className="text-star-dim">{t("project.targetDate")}</dt><dd>{data.project.target_date || t("common.none")}</dd></div><div><dt className="text-star-dim">{t("project.recentActivity")}</dt><dd>{formatDate(data.project.last_activity_at, true, lang)}</dd></div></dl></section>
    <section className="panel"><h2 className="mb-3 font-bold">{t("project.members")}<HelpTip topic="members" /></h2><div className="space-y-2">{data.members.map((member) => <div className="flex justify-between text-sm" key={member.id}><span>{member.name}<span className="ml-1 text-xs text-star-dim">{member.role}</span></span>{data.permissions.can_manage && <button aria-label={t("a11y.removeMember", { name: member.name })} className="text-xs text-danger" onClick={() => void api(`/projects/${data.project.id}/members/${member.id}`, { method: "DELETE" }).then(reload)}>{t("common.remove")}</button>}</div>)}</div>{data.permissions.can_manage && metadata && <form className="mt-4 flex gap-2" onSubmit={addMember}><select aria-label={t("a11y.addMember")} className="min-w-0 flex-1" name="user_id">{metadata.users.filter((user) => !data.members.some((member) => member.id === user.id) && user.id !== data.project.owner_id).map((user) => <option value={user.id} key={user.id}>{user.name}</option>)}</select><button className="btn !px-3">{t("project.join")}</button></form>}</section>
    {data.permissions.can_manage && <form className="panel space-y-3" onSubmit={saveSettings}><h2 className="font-bold">{t("project.settings")}</h2><label className="label">{t("projects.product")}</label><input aria-label={t("projects.product")} className="w-full" name="product" defaultValue={data.project.product} placeholder={t("projects.productPlaceholder")} /><label className="label">{t("projects.site")}</label><input aria-label={t("projects.site")} className="w-full" name="site" defaultValue={data.project.site} placeholder={t("projects.sitePlaceholder")} /><label className="label">{t("project.visibility")}<HelpTip topic="visibility" /></label><select aria-label={t("a11y.visibility")} className="w-full" name="visibility" defaultValue={data.project.visibility}><option value="all">{t("projects.visibility.all")}</option><option value="group">{t("projects.visibility.group")}</option><option value="private">{t("projects.visibility.private")}</option></select><label className="label">{t("common.status")}<HelpTip topic="status" /></label><select aria-label={t("a11y.projectStatus")} className="w-full" name="status" defaultValue={data.project.status}><option value="active">{t("status.active")}</option><option value="paused">{t("status.paused")}</option><option value="done">{t("status.done")}</option><option value="archived">{t("status.archived")}</option></select><button className="btn w-full">{t("project.saveSettings")}</button><button type="button" className="btn-secondary w-full" onClick={() => void archive()}>{t(data.project.status === "archived" ? "project.restore" : "project.archiveNow")}</button></form>}</aside></div><OkrPanel projectId={data.project.id} metadata={metadata} onChanged={reload} /></>;
}

function Updates({ data, reload }: { data: ProjectDetail; reload(): void }) {
  const { lang } = useLang();
  const t = useT();
  const [content, setContent] = useState(""); const [raw, setRaw] = useState(""); const [busy, setBusy] = useState(false); const [links, setLinks] = useState<ProgressLinksResponse | null>(null); const [toast, setToast] = useState("");
  const [mode, setMode] = useState<"entries" | "free">("entries");
  const [composeKey, setComposeKey] = useState(0); const [composeError, setComposeError] = useState("");
  const draft = async () => { if (!raw.trim()) return; setBusy(true); try { const result = await api<{ draft: string }>("/ai/draft-update", { method: "POST", body: JSON.stringify({ raw_text: raw, project_id: data.project.id, lang }) }); setContent(result.draft); } finally { setBusy(false); } };
  const save = async () => {
    const publishedContent = content;
    const result = await api<{ id: string }>(`/projects/${data.project.id}/progress-updates`, { method: "POST", body: JSON.stringify({ content: publishedContent, progress_snapshot: data.project.progress }) });
    setContent(""); setRaw(""); reload();
    if (!readProgressLinksPreference()) return;
    try {
      const suggestions = await api<ProgressLinksResponse>("/ai/progress-links", { method: "POST", body: JSON.stringify({ project_id: data.project.id, content: publishedContent, progress_update_id: result.id, lang }) });
      if (suggestions.complete.length || suggestions.create.length || suggestions.milestones.length || suggestions.events.length || suggestions.dates.length) setLinks(suggestions);
    } catch (error) {
      console.warn("progress link suggestions unavailable", error);
    }
  };
  /** 逐條輸入：使用者已指定日期、類型與對應任務，直接照做，不再猜文字。 */
  const publishEntries = async (entries: ProgressEntry[], composed: string, warnProgress: boolean) => {
    if (warnProgress && !window.confirm(t("compose.confirm", { count: entries.length }))) return;
    setBusy(true); setComposeError("");
    try {
      await api(`/projects/${data.project.id}/progress-updates`, { method: "POST", body: JSON.stringify({ content: composed, progress_snapshot: data.project.progress }) });
      const results = await Promise.allSettled(planEntryActions(entries, data.tasks, today()).map(async (action) => {
        const project = data.project.id;
        if (action.type === "complete") return api(`/tasks/${action.taskId}`, patchBody({ done: true }));
        if (action.type === "move") return api(`/tasks/${action.taskId}`, patchBody({ stage_id: action.stageId }));
        if (action.type === "setDate") return api(`/tasks/${action.taskId}`, patchBody({ due_date: action.dueDate }));
        if (action.type === "create") return api(`/projects/${project}/tasks`, { method: "POST", body: JSON.stringify({ title: action.title, stage_id: action.stageId, due_date: action.dueDate }) });
        if (action.type === "createDone") {
          const created = await api<{ id: string }>(`/projects/${project}/tasks`, { method: "POST", body: JSON.stringify({ title: action.title, stage_id: action.stageId, due_date: action.dueDate }) });
          return api(`/tasks/${created.id}`, patchBody({ done: true }));
        }
        return api(`/projects/${project}/milestones`, { method: "POST", body: JSON.stringify({ title: action.title, due_date: action.date, kind: action.type === "event" ? "event" : "milestone" }) });
      }));
      const failed = results.filter((result) => result.status === "rejected").length;
      // 部分失敗仍要重新載入：成功的那幾筆已經寫進去了。
      if (failed) setComposeError(t("compose.partialFailure", { count: failed }));
      setComposeKey((value) => value + 1);
      reload();
    } catch (cause) {
      setComposeError(cause instanceof Error ? cause.message : t("error.create"));
    } finally {
      setBusy(false);
    }
  };
  const applied = ({ completed, created, milestones, events, dates }: { completed: number; created: number; milestones: number; events: number; dates: number }) => {
    reload();
    setToast(t("progressLinks.appliedToast", { completed, created, milestones, events, dates }));
    window.setTimeout(() => setToast(""), 3500);
  };
  if (!data.progress_updates) return <Loading />;
  return <>{toast && <div className="fixed bottom-5 right-5 z-[60] border border-ok bg-nexus p-4 text-sm text-ok shadow-2xl" role="status">{toast}</div>}<div data-tour="progress-updates" className="grid gap-6 lg:grid-cols-5"><section className="panel lg:col-span-2"><h2 className="mb-4 font-bold">{t("project.newUpdate")}<HelpTip topic="progressUpdates" /></h2>{data.permissions.can_edit ? <>
      <div className="mb-4 flex gap-1 border-b border-nexus-line">{([["entries", "compose.modeEntries"], ["free", "compose.modeFree"]] as const).map(([key, labelKey]) => <button key={key} type="button" className={`border-b-2 px-3 py-2 text-sm font-medium ${mode === key ? "border-psi text-psi" : "border-transparent text-star-dim"}`} onClick={() => setMode(key)}>{t(labelKey)}</button>)}</div>
      {composeError && <ErrorBox message={composeError} />}
      {mode === "entries"
        ? <ProgressComposer key={composeKey} tasks={data.tasks} stages={data.stages} today={today()} busy={busy} onPublish={(entries, composed, warn) => void publishEntries(entries, composed, warn)} />
        : <><textarea className="mb-3 min-h-24 w-full" placeholder={t("project.rawPlaceholder")} value={raw} onChange={(e) => setRaw(e.target.value)} /><div className="mb-4 flex items-center gap-1"><button className="btn-secondary" disabled={busy} onClick={() => void draft()}>{t(busy ? "project.organizing" : "project.aiDraft")}</button><HelpTip topic="aiQuickWrite" /></div><textarea className="min-h-48 w-full" placeholder={t("project.updatePlaceholder")} value={content} onChange={(e) => setContent(e.target.value)} /><button className="btn mt-3" disabled={!content.trim()} onClick={() => void save()}>{t("project.publish")}</button></>}
    </> : <p className="text-sm text-star-dim">{t("project.noEdit")}</p>}</section><section className="space-y-4 lg:col-span-3">{data.progress_updates.length ? data.progress_updates.map((item) => <ProgressUpdateCard item={item} reload={reload} key={item.id} />) : <Empty>{t("project.noUpdates")}</Empty>}</section></div>{links && <ProgressLinkDialog response={links} projectId={data.project.id} stages={data.stages} tasks={data.tasks} onClose={() => setLinks(null)} onApplied={applied} />}</>;
}

function ProgressUpdateCard({ item, reload }: { item: ProgressUpdate; reload(): void }) {
  const { lang } = useLang();
  const t = useT();
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(item.content);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const save = async () => {
    if (!draft.trim()) return;
    setBusy(true); setError("");
    try {
      await api(`/progress-updates/${item.id}`, patchBody({ content: draft }));
      setEditing(false);
      reload();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : t("error.update"));
    } finally {
      setBusy(false);
    }
  };
  const remove = async () => {
    if (!window.confirm(t("project.deleteUpdateConfirm"))) return;
    setBusy(true); setError("");
    try {
      await api(`/progress-updates/${item.id}`, { method: "DELETE" });
      reload();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : t("error.operation"));
    } finally {
      setBusy(false);
    }
  };
  const cancel = () => { setDraft(item.content); setEditing(false); setError(""); };
  return <article className="panel"><div className="mb-3 flex items-start justify-between gap-3 text-xs text-star-dim"><span>{item.author_name}{item.is_support ? t("project.supportBy", { name: item.author_name }) : ""}</span><div className="flex items-center gap-1"><span>{formatDate(item.created_at, true, lang)}</span>{item.can_edit && <><button type="button" className="progress-update-edit" data-progress-update-edit aria-label={t("project.editUpdate")} title={t("project.editUpdate")} disabled={busy} onClick={() => { setDraft(item.content); setEditing(true); }}><svg aria-hidden="true" viewBox="0 0 24 24"><path d="m4 20 4.2-1 10.6-10.6-3.2-3.2L5 15.8 4 20Zm9.8-13 3.2 3.2M14.8 6l1.7-1.7a1.5 1.5 0 0 1 2.1 0l1.1 1.1a1.5 1.5 0 0 1 0 2.1L18 9.2" /></svg></button><button type="button" className="regwatch-row-delete" data-progress-update-delete aria-label={t("project.deleteUpdate")} title={t("project.deleteUpdate")} disabled={busy} onClick={() => void remove()}><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3m3 0-1 13H7L6 7m4 4v5m4-5v5" /></svg></button></>}</div></div>{error && <ErrorBox message={error} />}{editing ? <div><textarea className="min-h-32 w-full" value={draft} onChange={(event) => setDraft(event.target.value)} /><div className="mt-3 flex gap-2"><button className="btn" type="button" disabled={busy || !draft.trim()} onClick={() => void save()}>{t("common.save")}</button><button className="btn-secondary" type="button" disabled={busy} onClick={cancel}>{t("common.cancel")}</button></div></div> : <Markdown content={item.content} />}{item.edited_at && <p className="mt-3 text-xs text-star-dim">{t("project.editedAt", { date: formatProgressEditedAt(item.edited_at, lang) })}</p>}{isAutoGeneratedProgressUpdate(item.content) && <p className="mt-3 text-xs text-star-dim">{t("project.autoDeleteHint")}</p>}{item.progress_snapshot !== null && <div className="mt-4"><ProgressBar value={item.progress_snapshot} /></div>}</article>;
}

function Clinical({ data, reload }: { data: ProjectDetail; reload(): void }) {
  const t = useT(); const { lang } = useLang();
  const [enrollmentSubmitting, setEnrollmentSubmitting] = useState(false);
  if (!data.enrollments) return <Loading />;
  const target = data.clinical_settings?.target_n ?? 0; let total = 0; const chart = data.enrollments.map((item) => ({ date: item.record_date, 累計收案: total += Number(item.count), 目標: target })); const sites = data.enrollments.reduce<Record<string, number>>((result, item) => { const site = item.site || "未指定"; result[site] = (result[site] ?? 0) + Number(item.count); return result; }, {});
  const add = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = event.currentTarget; setEnrollmentSubmitting(true);
    try { await api(`/projects/${data.project.id}/clinical/enrollments`, { method: "POST", body: JSON.stringify(submitData(event)) }); form.reset(); reload(); }
    finally { setEnrollmentSubmitting(false); }
  };
  const setTarget = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/projects/${data.project.id}/clinical/settings`, { method: "PUT", body: JSON.stringify(submitData(event)) }); reload(); };
  return <div className="space-y-6"><div className="grid gap-6 lg:grid-cols-3"><section className="panel lg:col-span-2"><h2 className="mb-4 font-bold">{t("clinical.cumulative")}<HelpTip topic="clinicalEnrollment" /></h2><Suspense fallback={<div className="h-[300px]" />}><EnrollmentChart data={chart} /></Suspense></section><section className="panel"><p className="text-sm text-star-dim">{t("clinical.current")}</p><p className="my-2 text-4xl font-black text-psi">{total} <span className="text-base text-star-dim">/ {t("common.people", { count: target })}</span></p>{data.permissions.can_edit && <form className="mt-6 flex gap-2" onSubmit={setTarget}><input className="min-w-0 flex-1" name="target_n" type="number" min="0" defaultValue={target} /><button className="btn">{t("clinical.updateTarget")}</button></form>}</section></div>
    {data.permissions.can_edit && <form className="panel grid gap-3 md:grid-cols-5" onSubmit={add}><input name="record_date" type="date" defaultValue={today()} required /><input name="site" placeholder={t("clinical.site")} /><input name="count" type="number" min="0" placeholder={t("clinical.newCount")} required /><input name="note" placeholder={t("common.notes")} /><button className="btn" disabled={enrollmentSubmitting}>{t(enrollmentSubmitting ? "common.processing" : "clinical.record")}</button></form>}
    <div className="grid gap-6 lg:grid-cols-3"><section className="panel lg:col-span-2"><h2 className="mb-3 font-bold">{t("clinical.daily")}</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-nexus-line text-gold-bright"><th className="py-2">{t("common.date")}</th><th>{t("clinical.site")}</th><th>{t("clinical.count")}</th><th>{t("common.notes")}</th></tr></thead><tbody>{data.enrollments.map((item) => <tr className="border-b border-nexus-line" key={item.id}><td className="py-2">{item.record_date}</td><td>{item.site || t("common.none")}</td><td>{item.count}</td><td>{item.note}</td></tr>)}</tbody></table></div></section><section className="panel"><h2 className="mb-3 font-bold">{t("clinical.siteTotals")}</h2>{Object.entries(sites).map(([site, count]) => <div className="flex justify-between border-b py-2 text-sm" key={site}><span>{site}</span><strong>{t("common.people", { count })}</strong></div>)}</section></div></div>;
}

function Bd({ data, reload }: { data: ProjectDetail; reload(): void }) {
  const t = useT();
  const { lang } = useLang();
  const [feeSubmitting, setFeeSubmitting] = useState(false);
  const addCase = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api(`/projects/${data.project.id}/bd/cases`, { method: "POST", body: JSON.stringify(submitData(event)) }); event.currentTarget.reset(); reload(); };
  const addEvent = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = submitData(event); const caseId = String(values.case_id); delete values.case_id; await api(`/bd/cases/${caseId}/events`, { method: "POST", body: JSON.stringify(values) }); event.currentTarget.reset(); reload(); };
  const addFee = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = event.currentTarget; setFeeSubmitting(true);
    try { await api(`/projects/${data.project.id}/bd/fees`, { method: "POST", body: JSON.stringify(submitData(event)) }); form.reset(); reload(); }
    finally { setFeeSubmitting(false); }
  };
  const bdCases = data.bd_cases; const bdEvents = data.bd_events;
  if (!bdCases || !bdEvents) return <Loading />;
  return <div className="space-y-6">{data.permissions.can_edit && <form className="panel grid gap-3 md:grid-cols-4" onSubmit={addCase}><h2 className="font-bold md:col-span-4">{t("bd.newCase")}<HelpTip topic="bdCaseStatus" /></h2><input name="case_name" placeholder={t("bd.caseName")} required /><input name="product_name" placeholder={t("bd.product")} required /><input name="case_type" placeholder={t("bd.caseType")} required /><input name="submission_no" placeholder={t("bd.submissionNo")} /><select name="current_status">{bdStatuses.map(([value, key]) => <option value={value} key={value}>{t(key)}</option>)}</select><input name="submitted_at" type="date" /><input name="expected_approval" type="date" /><button className="btn">{t("bd.addCase")}</button></form>}
    <div className="grid gap-4 md:grid-cols-2">{bdCases.map((item) => <CaseCard key={item.id} item={item} canEdit={data.permissions.can_edit} reload={reload} events={bdEvents.filter((event) => event.case_id === item.id)} />)}</div>
    {data.permissions.can_edit && bdCases.length > 0 && <form className="panel grid gap-3 md:grid-cols-5" onSubmit={addEvent}><h2 className="font-bold md:col-span-5">{t("bd.newHistory")}<HelpTip topic="bdHistory" /></h2><select name="case_id">{bdCases.map((item) => <option value={item.id} key={item.id}>{item.case_name}</option>)}</select><input name="event_date" type="date" defaultValue={today()} required /><input name="event_type" placeholder={t("bd.eventPlaceholder")} required /><input name="description" placeholder={t("common.description")} required /><button className="btn">{t("bd.addHistory")}</button></form>}
    {data.permissions.can_view_fees && <section className="panel"><h2 className="mb-4 font-bold">{t("bd.fees")}<HelpTip topic="bdFees" /></h2>{data.permissions.can_edit && <form className="mb-4 grid gap-3 md:grid-cols-6" onSubmit={addFee}><input name="fee_date" type="date" defaultValue={today()} required /><select name="case_id"><option value="">{t("bd.noCase")}</option>{bdCases.map((item) => <option value={item.id} key={item.id}>{item.case_name}</option>)}</select><select name="category">{bdFeeCategories.map(([value, key]) => <option value={value} key={value}>{t(key)}</option>)}</select><input name="amount" type="number" min="0" placeholder={t("bd.amount")} required /><input name="currency" defaultValue="TWD" /><button className="btn" disabled={feeSubmitting}>{t(feeSubmitting ? "common.processing" : "bd.addFee")}</button></form>}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-nexus-line text-gold-bright"><th className="py-2">{t("common.date")}</th><th>{t("common.category")}</th><th>{t("bd.amount")}</th><th>{t("common.notes")}</th></tr></thead><tbody>{data.bd_fees?.map((fee) => <tr className="border-b border-nexus-line" key={fee.id}><td className="py-2">{fee.fee_date}</td><td>{t(bdFeeCategories.find(([value]) => value === fee.category)?.[1] ?? "bd.other")}</td><td>{fee.currency} {Number(fee.amount).toLocaleString(lang === "en" ? "en-US" : "zh-TW")}</td><td>{fee.note}</td></tr>)}</tbody></table></div><p className="mt-4 text-right font-bold">{t("bd.subtotal")}: TWD {(data.bd_fees ?? []).filter((fee) => fee.currency === "TWD").reduce((sum, fee) => sum + Number(fee.amount), 0).toLocaleString(lang === "en" ? "en-US" : "zh-TW")}</p></section>}</div>;
}

function CaseCard({ item, events, canEdit, reload }: { item: BdCase; events: BdEvent[]; canEdit: boolean; reload(): void }) {
  const t = useT();
  const setStatus = async (status: string) => { await api(`/bd/cases/${item.id}`, patchBody({ current_status: status })); reload(); };
  return <article className="panel"><div className="flex justify-between gap-3"><div><p className="text-xs text-star-dim">{item.case_type} · {item.product_name}</p><h3 className="mt-1 font-bold">{item.case_name}</h3></div><select value={item.current_status} disabled={!canEdit} onChange={(e) => void setStatus(e.target.value)}>{bdStatuses.map(([value, key]) => <option value={value} key={value}>{t(key)}</option>)}</select></div><p className="mt-3 text-sm text-star-dim">{t("bd.submissionNo")}: {item.submission_no || "—"} · {t("bd.expectedApproval", { date: item.expected_approval || "—" })}</p><div className="mt-4 space-y-3 border-l-2 border-gold-dim pl-4">{events.map((event) => <div key={event.id}><p className="text-sm font-medium">{event.event_type} · {event.event_date}</p><p className="text-xs text-star-dim">{event.description}</p></div>)}</div></article>;
}

/**
 * 同產品的其他專案，做成一條快速切換帶。放在標題下方而不是側欄，因為切換是導覽動作，
 * 應該與分頁列在同一個視線落點，不必先捲到頁尾。沒有相關專案時整條不出現。
 */
function RelatedStrip({ current, siblings }: { current: Project; siblings: SwitchableProject[] }) {
  const t = useT();
  const related = relatedProjects(siblings, current);
  if (!related.length) return null;
  return <div className="mb-4 flex flex-wrap items-center gap-2 border border-nexus-line bg-nexus-raised px-3 py-2">
    <span className="text-xs font-semibold text-gold-bright">{t("projects.productCount", { product: current.product, count: related.length + 1 })}</span>
    {related.map((item) => <Link key={item.id} to={`/projects/${item.id}`}
      className="border border-nexus-line px-2 py-1 text-sm hover:border-psi hover:text-psi">{item.name}</Link>)}
  </div>;
}
