import { useEffect, useState } from "react";
import { api, today } from "../api";
import { useAuth } from "../auth";
import { Empty, Loading, Markdown, PageHeader } from "../components/UI";
import type { Metadata } from "../types";

interface Summary { projects: Array<{ id: string; name: string; group_name: string; progress: number; progress_change: number; updates: number; completed_tasks: number; enrollments: number; bd_events: number }>; totals: { completed_tasks: number; enrollments: number; bd_events: number }; fees: Array<{ project_id: string; currency: string; total: number }> }
interface AiReport { id: string; period_start: string; period_end: string; scope_name: string; content_md: string; created_at: string }

function monthStart() { const value = today(); return `${value.slice(0, 8)}01`; }
function weekRange(offset = 0) { const current = new Date(); const taipei = new Date(current.toLocaleString("en-US", { timeZone: "Asia/Taipei" })); const day = taipei.getDay() || 7; taipei.setDate(taipei.getDate() - day + 1 + offset * 7); const start = taipei.toISOString().slice(0, 10); taipei.setDate(taipei.getDate() + 6); return { from: start, to: taipei.toISOString().slice(0, 10) }; }

export function ReportsPage() {
  const { user } = useAuth(); const currentWeek = weekRange(); const [range, setRange] = useState({ from: currentWeek.from, to: currentWeek.to, group: "" }); const [summary, setSummary] = useState<Summary | null>(null); const [reports, setReports] = useState<AiReport[]>([]); const [meta, setMeta] = useState<Metadata | null>(null);
  const load = () => api<Summary>(`/reports/summary?${new URLSearchParams(range)}`).then(setSummary);
  useEffect(() => { void load(); }, [range]); useEffect(() => { void api<{ reports: AiReport[] }>("/reports/ai").then((data) => setReports(data.reports)); void api<Metadata>("/metadata").then(setMeta); }, []);
  const preset = (value: string) => { if (value === "this-week") setRange({ ...range, ...weekRange() }); else if (value === "last-week") setRange({ ...range, ...weekRange(-1) }); else setRange({ ...range, from: monthStart(), to: today() }); };
  const csv = (kind: "summary" | "fees") => { if (!summary) return; const rows = kind === "summary" ? [["專案", "組別", "目前進度", "進度變化", "完成任務", "新增收案", "BD事件"], ...summary.projects.map((p) => [p.name, p.group_name, p.progress, p.progress_change, p.completed_tasks, p.enrollments, p.bd_events])] : [["專案ID", "幣別", "費用小計"], ...summary.fees.map((f) => [f.project_id, f.currency, f.total])]; const content = `\uFEFF${rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\r\n")}`; const url = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${kind}-${range.from}-${range.to}.csv`; anchor.click(); URL.revokeObjectURL(url); };
  const regenerate = async () => { await api("/reports/ai/regenerate", { method: "POST", body: JSON.stringify({ period_start: range.from, period_end: range.to }) }); const result = await api<{ reports: AiReport[] }>("/reports/ai"); setReports(result.reports); };
  return <><PageHeader title="報表" description="依可見專案彙整期間成果；列印時自動隱藏導覽與操作按鈕。" actions={<div className="flex gap-2 no-print"><button className="btn-secondary" onClick={() => window.print()}>列印</button><button className="btn-secondary" onClick={() => csv("summary")}>匯出 CSV</button>{user?.role === "admin" && <button className="btn" onClick={() => void regenerate()}>立即產生週報</button>}</div>} />
    <section className="panel mb-6 grid gap-3 md:grid-cols-5 no-print"><select onChange={(e) => preset(e.target.value)}><option value="this-week">本週</option><option value="last-week">上週</option><option value="month">本月</option></select><input type="date" value={range.from} onChange={(e) => setRange({ ...range, from: e.target.value })} /><input type="date" value={range.to} onChange={(e) => setRange({ ...range, to: e.target.value })} /><select value={range.group} onChange={(e) => setRange({ ...range, group: e.target.value })}><option value="">全部組別</option>{meta?.groups.map((g) => <option value={g.id} key={g.id}>{g.name}</option>)}</select><button className="btn-secondary" onClick={() => csv("fees")}>匯出費用 CSV</button></section>
    {!summary ? <Loading /> : <><div className="mb-6 grid gap-4 sm:grid-cols-3"><Stat label="完成任務" value={summary.totals.completed_tasks} /><Stat label="新增收案" value={summary.totals.enrollments} /><Stat label="BD 事件" value={summary.totals.bd_events} /></div><section className="panel mb-6 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-nexus-line text-gold-bright"><th className="py-2">專案</th><th>進度</th><th>變化</th><th>更新</th><th>完成任務</th><th>收案</th><th>BD事件</th></tr></thead><tbody>{summary.projects.map((p) => <tr className="border-b border-nexus-line" key={p.id}><td className="py-3 font-medium">{p.name}<span className="ml-2 text-xs text-star-dim">{p.group_name}</span></td><td>{p.progress}%</td><td className={p.progress_change >= 0 ? "text-ok" : "text-danger"}>{p.progress_change >= 0 ? "+" : ""}{p.progress_change}%</td><td>{p.updates}</td><td>{p.completed_tasks}</td><td>{p.enrollments}</td><td>{p.bd_events}</td></tr>)}</tbody></table></section></>}
    <h2 className="mb-4 text-xl font-bold">AI 週報</h2>{reports.length ? <div className="grid gap-5 lg:grid-cols-2">{reports.map((report) => <article className="panel" key={report.id}><p className="mb-3 text-xs font-medium text-psi">{report.scope_name} · {report.period_start} ～ {report.period_end}</p><Markdown content={report.content_md} /></article>)}</div> : <Empty>{user?.role === "admin" ? "尚未產生 AI 週報" : "基於保密專案權限，AI 週報由管理員檢視；上方即時摘要仍依您的可見範圍呈現。"}</Empty>}
  </>;
}
function Stat({ label, value }: { label: string; value: number }) { return <div className="panel"><p className="text-sm text-star-dim">{label}</p><p className="mt-2 text-3xl font-black text-psi">{value}</p></div>; }
