import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { api, today } from "../api";
import { CHART } from "../chartTheme";
import { PageHeader, RiskBadge } from "../components/UI";
import { addDays, daysBetween, ganttPosition } from "../utils/dates";

interface TimelineProject { id: string; name: string; start_date: string | null; target_date: string | null; progress: number; risk_level: string | null; group: string }

export function TimelinePage() {
  const [projects, setProjects] = useState<TimelineProject[]>([]); useEffect(() => { void api<{ projects: TimelineProject[] }>("/timeline").then((result) => setProjects(result.projects)); }, []);
  const dates = projects.flatMap((project) => [project.start_date, project.target_date]).filter((value): value is string => !!value).sort(); const start = dates[0] ?? today(); const end = dates.at(-1) ?? addDays(start, 90); const width = Math.max(820, (daysBetween(start, end) + 2) * 8); const label = 240; const row = 56; const height = 55 + projects.length * row;
  const weeks = useMemo(() => Array.from({ length: Math.ceil((daysBetween(start, end) + 1) / 7) + 1 }, (_, index) => addDays(start, index * 7)), [start, end]);
  return <><PageHeader title="全域時間軸" description="只顯示您可見的進行中專案、進度與風險。" /><section className="panel overflow-x-auto"><svg className="chart-surface" width={label + width} height={height} role="img" aria-label="所有進行中專案時間軸"><rect width="100%" height="100%" fill={CHART.nexus} />{weeks.map((date) => { const x = label + ganttPosition(date, start, end, width); return <g key={date}><line x1={x} x2={x} y1="30" y2={height} stroke={CHART.line} /><text x={x + 3} y="20" fontSize="10" fill={CHART.starDim}>{date.slice(5)}</text></g>; })}{projects.map((project, index) => { const y = 45 + index * row; const projectStart = project.start_date ?? start; const projectEnd = project.target_date ?? projectStart; const x = label + ganttPosition(projectStart, start, end, width); const barWidth = Math.max(8, ganttPosition(projectEnd, start, end, width) - ganttPosition(projectStart, start, end, width)); return <g key={project.id}><foreignObject x="4" y={y - 7} width={label - 12} height="48"><Link to={`/projects/${project.id}`} className="block text-sm font-semibold text-star hover:text-psi">{project.name}<span className="mt-1 block text-xs font-normal text-star-dim">{project.group} · {riskLabel(project.risk_level)}</span></Link></foreignObject><Link to={`/projects/${project.id}`}><rect x={x} y={y} width={barWidth} height="22" rx="8" fill={CHART.raised}><title>{project.name}：{projectStart} ～ {projectEnd}</title></rect><rect x={x} y={y} width={barWidth * project.progress / 100} height="22" rx="8" fill={project.progress >= 100 ? CHART.gold : CHART.psi} style={{ filter: `drop-shadow(0 0 6px ${CHART.psiGlow})` }} /><text x={x + 6} y={y + 15} fill={CHART.star} fontSize="11">{project.progress}%</text></Link></g>; })}<line x1={label + ganttPosition(today(), start, end, width)} x2={label + ganttPosition(today(), start, end, width)} y1="30" y2={height} stroke={CHART.psi} strokeWidth="2" /></svg></section><div className="mt-4 flex gap-3 text-sm"><RiskBadge level="low" /><RiskBadge level="medium" /><RiskBadge level="high" /></div></>;
}

function riskLabel(level: string | null): string { return level === "high" ? "高風險" : level === "medium" ? "中風險" : level === "low" ? "低風險" : "未分析"; }
