import { useEffect, useState, type FormEvent } from "react";
import { api, patchBody, today } from "../api";
import { Empty, PageHeader } from "../components/UI";
import type { Project } from "../types";

interface Todo { id: string; title: string; due_date: string | null; done: number; project_id: string | null; project_name: string | null }
export function TodosPage() {
  const [todos, setTodos] = useState<Todo[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [toast, setToast] = useState(""); const load = () => api<{ todos: Todo[] }>("/todos").then((d) => setTodos(d.todos)); useEffect(() => { void load(); }, []); useEffect(() => { void api<{ projects: Project[] }>("/projects").then((data) => setProjects(data.projects)); }, []);
  const add = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await api("/todos", { method: "POST", body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); event.currentTarget.reset(); load(); };
  const groups = [{ title: "今日", items: todos.filter((t) => !t.done && t.due_date === today()) }, { title: "逾期", items: todos.filter((t) => !t.done && !!t.due_date && t.due_date < today()) }, { title: "未排程", items: todos.filter((t) => !t.done && !t.due_date) }, { title: "之後", items: todos.filter((t) => !t.done && !!t.due_date && t.due_date > today()) }, { title: "已完成", items: todos.filter((t) => !!t.done) }];
  const toggle = async (item: Todo, done: boolean) => { const result = await api<{ project_progress?: number }>(`/todos/${item.id}`, patchBody({ done })); if (done && item.project_name && result.project_progress !== undefined) { setToast(`已完成「${item.title}」，${item.project_name} 進度更新為 ${result.project_progress}%`); window.setTimeout(() => setToast(""), 3500); } await load(); };
  return <><PageHeader title="我的待辦" description="把每日工作與專案連在一起。" />{toast && <div className="fixed right-5 top-20 z-50 rounded-lg bg-emerald-600 px-4 py-3 text-sm text-white shadow-lg">{toast}</div>}<form className="card mb-6 grid gap-3 md:grid-cols-4" onSubmit={add}><input name="title" placeholder="新增待辦事項" required /><input name="due_date" type="date" /><select name="project_id"><option value="">不關聯專案</option>{projects.map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select><button className="btn">新增</button></form><div className="grid gap-5 lg:grid-cols-2">{groups.map((group) => <section className="card" key={group.title}><h2 className="mb-3 font-bold">{group.title} <span className="text-xs text-slate-400">{group.items.length}</span></h2>{group.items.length ? <div className="space-y-2">{group.items.map((item) => <label className="flex items-center gap-3 rounded-lg border border-slate-100 p-3" key={item.id}><input type="checkbox" checked={!!item.done} onChange={(e) => void toggle(item, e.target.checked)} /><span className={`flex-1 text-sm ${item.done ? "line-through text-slate-400" : ""}`}>{item.title}{item.project_name && <small className="ml-2 text-brand-600">{item.project_name}</small>}</span><span className="text-xs text-slate-400">{item.due_date}</span><button className="text-red-400" onClick={(e) => { e.preventDefault(); void api(`/todos/${item.id}`, { method: "DELETE" }).then(load); }}>×</button></label>)}</div> : <Empty>沒有項目</Empty>}</section>)}</div></>;
}
