import { useEffect, useState, type FormEvent } from "react";
import { api, patchBody } from "../api";
import type { AutomationRule, Metadata, ProjectDetail } from "../types";
import { Empty, ErrorBox } from "./UI";

export function AutomationPanel({ data, metadata }: { data: ProjectDetail; metadata: Metadata | null }) {
  const [rules, setRules] = useState<AutomationRule[]>([]); const [canManage, setCanManage] = useState(false); const [error, setError] = useState(""); const [trigger, setTrigger] = useState("task_done"); const [action, setAction] = useState("notify_user");
  const load = () => api<{ rules: AutomationRule[]; can_manage: boolean }>(`/projects/${data.project.id}/rules`).then((result) => { setRules(result.rules); setCanManage(result.can_manage); });
  useEffect(() => { void load(); }, [data.project.id]);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); const body = Object.fromEntries(new FormData(event.currentTarget)); try { await api(`/projects/${data.project.id}/rules`, { method: "POST", body: JSON.stringify(body) }); event.currentTarget.reset(); setTrigger("task_done"); setAction("notify_user"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "建立規則失敗"); } };
  const toggle = async (rule: AutomationRule) => { await api(`/rules/${rule.id}`, patchBody({ enabled: !rule.enabled })); await load(); };
  const remove = async (rule: AutomationRule) => { if (!window.confirm(`刪除規則「${rule.name}」？`)) return; await api(`/rules/${rule.id}`, { method: "DELETE" }); await load(); };
  const invalidAssign = action === "assign_task_to" && !["task_done", "task_moved_to_stage"].includes(trigger);
  return <div data-tour="automation" className="space-y-5">{error && <ErrorBox message={error} />}{canManage && <form className="panel grid gap-3 md:grid-cols-2" onSubmit={create}><h2 className="font-bold md:col-span-2">新增「當…就…」規則</h2><div><label className="label">規則名稱</label><input className="w-full" name="name" placeholder="例如：完成後通知臨床組" required /></div><div><label className="label">當</label><select className="w-full" name="trigger_type" value={trigger} onChange={(e) => setTrigger(e.target.value)}><option value="task_done">任務完成</option><option value="task_moved_to_stage">任務移入階段</option><option value="milestone_done">里程碑完成</option><option value="progress_reached">進度達門檻</option></select></div>{trigger === "task_moved_to_stage" && <div><label className="label">階段</label><select className="w-full" name="trigger_param">{data.stages.map((stage) => <option value={stage.id} key={stage.id}>{stage.name}</option>)}</select></div>}{trigger === "progress_reached" && <div><label className="label">門檻 %</label><input className="w-full" name="trigger_param" type="number" min="1" max="100" defaultValue="50" /></div>}<div><label className="label">就</label><select className="w-full" name="action_type" value={action} onChange={(e) => setAction(e.target.value)}><option value="notify_user">通知成員</option><option value="assign_task_to">將該任務指派給</option><option value="create_todo_for">為成員建立待辦</option><option value="log_update">寫一筆進度紀錄</option></select></div>{action !== "log_update" && <div><label className="label">成員</label><select className="w-full" name="action_param_user">{metadata?.users.map((user) => <option value={user.id} key={user.id}>{user.name}</option>)}</select></div>}<div className="md:col-span-2"><label className="label">通知／待辦／紀錄文字</label><input className="w-full" name="action_param_text" placeholder="規則觸發時使用的文字" /></div>{invalidAssign && <p className="text-sm text-danger md:col-span-2">指派任務只適用任務完成或移入階段。</p>}<button className="btn md:col-span-2" disabled={invalidAssign}>建立規則</button></form>}<section className="panel"><h2 className="mb-4 font-bold">規則清單</h2>{rules.length ? <div className="space-y-3">{rules.map((rule) => <article className="flex flex-wrap items-center gap-3 rounded-lg border border-nexus-line p-4" key={rule.id}><span className={`h-2.5 w-2.5 rounded-full ${rule.enabled ? "border border-ok bg-void" : "bg-nexus-line"}`} /><div className="min-w-0 flex-1"><p className="font-medium">{rule.name}</p><p className="text-xs text-star-dim">當 {triggerLabel[rule.trigger_type]}，就 {actionLabel[rule.action_type]}</p></div>{canManage && <><button className="btn-secondary !px-3 !py-1.5" onClick={() => void toggle(rule)}>{rule.enabled ? "停用" : "啟用"}</button><button className="text-xs text-danger" onClick={() => void remove(rule)}>刪除</button></>}</article>)}</div> : <Empty>尚未建立自動化規則</Empty>}</section></div>;
}

const triggerLabel: Record<string, string> = { task_done: "任務完成", task_moved_to_stage: "任務移入指定階段", milestone_done: "里程碑完成", progress_reached: "進度達門檻" };
const actionLabel: Record<string, string> = { notify_user: "通知成員", assign_task_to: "指派任務", create_todo_for: "建立待辦", log_update: "寫進度紀錄" };

