import { useEffect, useState } from "react";
import { api, formatDate, patchBody } from "../api";
import type { Metadata, ProjectDetail, Task, TaskComment } from "../types";
import { ErrorBox, Markdown } from "./UI";
import { ProjectFiles } from "./ProjectFiles";

interface Mentionable { id: string; name: string }

export function TaskDrawer({ task, data, metadata, onClose, reload }: { task: Task; data: ProjectDetail; metadata: Metadata | null; onClose(): void; reload(): void }) {
  const [form, setForm] = useState(task); const [comments, setComments] = useState<TaskComment[]>([]); const [mentionables, setMentionables] = useState<Mentionable[]>([]); const [comment, setComment] = useState(""); const [summary, setSummary] = useState<{ summary: string; unresolved: string[] } | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { setForm(task); }, [task]);
  const loadComments = () => api<{ comments: TaskComment[] }>(`/tasks/${task.id}/comments`).then((result) => setComments(result.comments));
  useEffect(() => { void loadComments(); void api<{ users: Mentionable[] }>(`/projects/${data.project.id}/mentionables`).then((result) => setMentionables(result.users)); }, [task.id, data.project.id]);
  const save = async () => { setError(""); try { await api(`/tasks/${task.id}`, patchBody({ title: form.title, description: form.description, assignee_id: form.assignee_id, start_date: form.start_date, due_date: form.due_date, done: !!form.done })); reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "儲存失敗"); } };
  const toggleDependency = async (id: string, enabled: boolean) => { setError(""); try { if (enabled) await api(`/tasks/${task.id}/dependencies`, { method: "POST", body: JSON.stringify({ depends_on_task_id: id }) }); else await api(`/tasks/${task.id}/dependencies/${id}`, { method: "DELETE" }); reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "依賴更新失敗"); } };
  const sendComment = async () => { if (!comment.trim()) return; await api(`/tasks/${task.id}/comments`, { method: "POST", body: JSON.stringify({ content: comment }) }); setComment(""); await loadComments(); reload(); };
  const summarize = async () => { setBusy(true); try { setSummary(await api<{ summary: string; unresolved: string[] }>("/ai/task-summary", { method: "POST", body: JSON.stringify({ task_id: task.id }) })); } finally { setBusy(false); } };
  const mentionQuery = comment.match(/@([^\s@]*)$/)?.[1] ?? null;
  const candidates = mentionQuery === null ? [] : mentionables.filter((user) => user.name.includes(mentionQuery)).slice(0, 6);
  const insertMention = (name: string) => setComment(comment.replace(/@[^\s@]*$/, `@${name} `));
  return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/35" onMouseDown={onClose}><aside data-tour="task-drawer" className="h-full w-full max-w-2xl overflow-y-auto bg-white p-5 shadow-2xl" onMouseDown={(e) => e.stopPropagation()}><header className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold">任務內容</h2><button className="btn-secondary !px-3 !py-1.5" onClick={onClose}>關閉</button></header>{error && <ErrorBox message={error} />}
    <div className="space-y-4"><label className="label">標題</label><input className="w-full" value={form.title} disabled={!data.permissions.can_edit} onChange={(e) => setForm({ ...form, title: e.target.value })} /><label className="label">描述</label><textarea className="min-h-24 w-full" value={form.description} disabled={!data.permissions.can_edit} onChange={(e) => setForm({ ...form, description: e.target.value })} /><div className="grid gap-3 sm:grid-cols-3"><div><label className="label">負責人</label><select className="w-full" value={form.assignee_id ?? ""} disabled={!data.permissions.can_edit} onChange={(e) => setForm({ ...form, assignee_id: e.target.value || null })}><option value="">未指派</option>{metadata?.users.map((user) => <option value={user.id} key={user.id}>{user.name}</option>)}</select></div><div><label className="label">起日</label><input className="w-full" type="date" value={form.start_date ?? ""} disabled={!data.permissions.can_edit} onChange={(e) => setForm({ ...form, start_date: e.target.value || null })} /></div><div><label className="label">訖日</label><input className="w-full" type="date" value={form.due_date ?? ""} disabled={!data.permissions.can_edit} onChange={(e) => setForm({ ...form, due_date: e.target.value || null })} /></div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!form.done} disabled={!data.permissions.can_edit} onChange={(e) => setForm({ ...form, done: e.target.checked ? 1 : 0 })} />任務已完成</label>{data.permissions.can_edit && <button className="btn" onClick={() => void save()}>儲存任務</button>}</div>
    <section className="mt-7 border-t pt-5"><h3 className="mb-3 font-bold">前置依賴</h3><div className="grid gap-2 sm:grid-cols-2">{data.tasks.filter((item) => item.id !== task.id).map((item) => <label className="flex items-center gap-2 rounded-lg border border-slate-100 p-2 text-sm" key={item.id}><input type="checkbox" checked={task.dependency_ids?.includes(item.id)} disabled={!data.permissions.can_edit} onChange={(e) => void toggleDependency(item.id, e.target.checked)} />{item.title}</label>)}</div></section>
    <section className="mt-7 border-t pt-5"><div className="mb-3 flex items-center justify-between"><h3 className="font-bold">AI 任務摘要</h3><button className="btn-secondary !px-3 !py-1.5" disabled={busy} onClick={() => void summarize()}>{busy ? "摘要中…" : "產生摘要"}</button></div>{summary && <div className="rounded-lg bg-brand-50 p-4 text-sm"><p>{summary.summary}</p>{summary.unresolved.length > 0 && <><p className="mt-3 font-semibold">未決事項</p><ul className="list-disc pl-5">{summary.unresolved.map((item) => <li key={item}>{item}</li>)}</ul></>}</div>}</section>
    <section className="mt-7 border-t pt-5"><h3 className="mb-3 font-bold">附件</h3><ProjectFiles projectId={data.project.id} taskId={task.id} canEdit={data.permissions.can_edit} compact onChanged={reload} /></section>
    <section className="mt-7 border-t pt-5"><h3 className="mb-3 font-bold">留言</h3><div className="space-y-3">{comments.map((item) => <article className="rounded-lg bg-slate-50 p-3" key={item.id}><div className="mb-2 flex justify-between text-xs text-slate-400"><span>{item.author_name}</span><span title={formatDate(item.created_at, true)}>{relativeTime(item.created_at)}</span></div><Markdown content={item.content} /></article>)}</div>{data.permissions.can_edit && <div className="relative mt-4"><textarea className="min-h-20 w-full" placeholder="留言；輸入 @ 提及成員" value={comment} onChange={(e) => setComment(e.target.value)} />{candidates.length > 0 && <div className="absolute bottom-full mb-1 w-56 rounded-lg border bg-white p-1 shadow-lg">{candidates.map((user) => <button className="block w-full rounded px-3 py-2 text-left text-sm hover:bg-slate-50" key={user.id} onClick={() => insertMention(user.name)}>@{user.name}</button>)}</div>}<button className="btn mt-2" disabled={!comment.trim()} onClick={() => void sendComment()}>送出留言</button></div>}</section>
  </aside></div>;
}

function relativeTime(value: string): string {
  const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000));
  if (seconds < 60) return "剛剛";
  if (seconds < 3600) return `${Math.floor(seconds / 60)} 分鐘前`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)} 小時前`;
  if (seconds < 604800) return `${Math.floor(seconds / 86400)} 天前`;
  return formatDate(value);
}
