export const CHART = {
  void: "rgb(var(--color-void))",
  nexus: "rgb(var(--color-nexus))",
  raised: "rgb(var(--color-nexus-raised))",
  line: "rgb(var(--color-nexus-line))",
  gold: "rgb(var(--color-gold))",
  goldBright: "rgb(var(--color-gold-bright))",
  psi: "rgb(var(--color-psi))",
  psiDeep: "rgb(var(--color-psi-deep))",
  psiGlow: "rgb(var(--color-psi) / .35)",
  star: "rgb(var(--color-star))",
  starDim: "rgb(var(--color-star-dim))",
  ok: "rgb(var(--color-ok))",
  warn: "rgb(var(--color-warn))",
  danger: "rgb(var(--color-danger))",
} as const;
