import type { Lang } from "./i18n/LangContext";
import { parseServerDate } from "./utils/server-date";

export function isAutoGeneratedProgressUpdate(content: string): boolean {
  return content.startsWith("✔ 完成");
}

export function formatProgressEditedAt(value: string, lang: Lang): string {
  const parts = new Intl.DateTimeFormat(lang === "en" ? "en-CA" : "zh-TW", {
    timeZone: "Asia/Taipei",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hourCycle: "h23",
  }).formatToParts(parseServerDate(value));
  const part = (type: Intl.DateTimeFormatPartTypes) => parts.find((item) => item.type === type)?.value ?? "";
  return `${part("year")}/${part("month")}/${part("day")} ${part("hour")}:${part("minute")}`;
}
